Repository DEFRA/sroc-charging-module-api, pull requests merged in 2020-10, with the labels that each got.

#1 Set up CI
  .nvmrc
  .travis.yml
  README.md
  sonar-project.properties
Labels: enhancement

#2 Remove `host` from server.config.js
  config/server.config.js
Labels: housekeeping

#4 Add disinfect plugin to santize inputs to the API
  app/plugins/disinfect.plugin.js
  package-lock.json
  package.json
  server.js
Labels: enhancement

#5 Enable show scope option in Blipp plugin
  app/plugins/blipp.plugin.js
Labels: housekeeping

#6 Add Airbrake error logging to the project
  .env.example
  .travis.yml
  app/controllers/airbrake.controller.js
  app/plugins/airbrake.plugin.js
  app/plugins/router.plugin.js
  app/routes/airbrake.routes.js
  config/airbrake.config.js
  package-lock.json
  package.json
  server.js
  test/README.md
  test/controllers/airbrake.controller.test.js
  test/support/helpers/authorisation.helper.js
Labels: enhancement

#9 Implement Rules Service
  .env.example
  .travis.yml
  app/services/rules.service.js
  config/rules_service.config.js
  package-lock.json
  package.json
  test/services/rules.service.test.js
  test/support/fixtures/wrls/rules_service_request.json
  test/support/fixtures/wrls/rules_service_response.json
  test/support/helpers/rules.service.helper.js
Labels: enhancement

#10 Implement Calculate Charge Service
  .env.example
  .travis.yml
  app/services/calculate_charge.service.js
  app/services/rules.service.js
  config/rules_service.config.js
  test/services/calculate_charge.service.test.js
  test/services/rules.service.test.js
Labels: enhancement

#13 Create Charge model
  app/models/charge.model.js
  test/models/charge.model.test.js
  test/support/fixtures/charge.json
Labels: enhancement

#15 Fix airbrake controller test
  app/controllers/regimes.controller.js
  app/models/authorised_system.model.js
  app/models/index.js
  app/models/regime.model.js
  db/index.js
  test/controllers/airbrake.controller.test.js
  test/models/charge.model.test.js
  test/services/rules.service.test.js
  test/support/helpers/database.helper.js
  test/support/helpers/index.js
  test/support/helpers/rules_service.helper.js
Labels: bug, housekeeping

#14 Create request-to-charge translator
  app/models/charge.model.js
  app/translators/base.translator.js
  app/translators/charge.translator.js
  test/models/charge.model.test.js
  test/support/fixtures/charge.json
  test/translators/base.translator.js
Labels: enhancement

#11 Move airbrake controller to `/admin/health`
  app/controllers/admin/health/airbrake.controller.js
  app/routes/airbrake.routes.js
  test/controllers/admin/health/airbrake.controller.test.js
Labels: housekeeping

#18 Create charge-to-rules service presenter
  app/presenters/base.presenter.js
  app/presenters/rules_service.presenter.js
  test/presenters/base.presenter.js
Labels: enhancement

#12 Enable JWT token expiry checking
  .env.example
  app/auth/jwt_strategy.auth.js
  config/authentication.config.js
  test/controllers/admin/health/airbrake.controller.test.js
  test/features/authentication.test.js
  test/features/authorisation.test.js
  test/support/helpers/authorisation.helper.js
  test/support/helpers/authorised_system.helper.js
  test/support/helpers/database.helper.js
  test/support/helpers/index.js
  test/support/helpers/route.helper.js
Labels: enhancement

#21 Fix some sonarcloud code smells
  app/auth/jwt_strategy.auth.js
  app/controllers/regimes.controller.js
Labels: housekeeping

#23 Add check for use of `only()` in tests to travis
  .travis.yml
Labels: housekeeping

#22 Add Unescape sanitized HTML characters plugin
  app/plugins/index.js
  app/plugins/unescape.plugin.js
  server.js
  test/features/sanitise_payloads.test.js
  test/support/helpers/route.helper.js
Labels: enhancement

#24 Add logging plugin
  .env.example
  app/hooks/on_credentials.hook.js
  app/plugins/airbrake.plugin.js
  app/plugins/hapi_pino.plugin.js
  app/plugins/index.js
  config/index.js
  config/test.config.js
  package-lock.json
  package.json
  server.js
  test/features/logging.test.js
Labels: enhancement

#27 Create rules service translator
  app/models/charge.model.js
  app/translators/charge.translator.js
  app/translators/index.js
  app/translators/rules_service.translator.js
  test/support/fixtures/charge.json
  test/support/fixtures/wrls/rules_service_response.json
  test/translators/charge.translator.test.js
  test/translators/rules_service.translator.test.js
Labels: enhancement

#29 Amend chargeValue and baselineCharge to be integers
  app/models/charge.model.js
Labels: enhancement

#30 Create charge to user presenter
  app/presenters/charge.presenter.js
  app/presenters/index.js
Labels: enhancement

#32 Update calculate charge service based on recent discussion
  app/services/calculate_charge.service.js
  test/services/rules.service.test.js
Labels: enhancement
