Repository DEFRA/sroc-charging-module-api, pull requests merged in 2020-12, with the labels that each got.

#71 Add pre-sroc bill run translator
  app/translators/bill_run.translator.js
  app/translators/index.js
  test/translators/bill_run.translator.test.js
Labels: enhancement

#66 Add authorised systems index endpoint
  app/controllers/admin/authorised_systems.controller.js
  app/controllers/index.js
  app/plugins/router.plugin.js
  app/routes/authorised_system.routes.js
  app/routes/index.js
  app/services/index.js
  app/services/list_authorised_systems.service.js
  test/controllers/admin/authorised_systems.controller.test.js
  test/services/list_authorised_systems.service.test.js
Labels: enhancement

#67 Add authorised systems show endpoint
  app/controllers/admin/authorised_systems.controller.js
  app/routes/authorised_system.routes.js
  app/services/index.js
  app/services/show_authorised_system.service.js
  test/controllers/admin/authorised_systems.controller.test.js
  test/services/show_authorised_system.service.test.js
Labels: enhancement

#72 Add bill run table and model
  app/models/authorised_system.model.js
  app/models/bill_run.model.js
  app/models/index.js
  app/models/regime.model.js
  db/migrations/20201127163958_create_bill_runs.js
Labels: enhancement

#77 Fix calculate charge dependence on unknown region
  app/controllers/sroc/calculate_charge.controller.js
  app/presenters/rules_service.presenter.js
  app/routes/calculate_charge.routes.js
  app/services/rules.service.js
  app/translators/index.js
  app/translators/sroc_charge.translator.js
  config/rules_service.config.js
  test/controllers/calculate_charge.controller.test.js
  test/services/rules.service.test.js
  test/support/helpers/rules_service.helper.js
  test/translators/sroc_charge.translator.test.js
Labels: bug

#68 Add new create authorised system endpoint
  app/controllers/admin/authorised_systems.controller.js
  app/routes/authorised_system.routes.js
  app/services/create_authorised_system.service.js
  app/services/index.js
  app/translators/authorised_system.translator.js
  app/translators/index.js
  db/migrations/20201127100927_alter_authorised_systems.js
  test/controllers/admin/authorised_systems.controller.test.js
  test/services/create_authorised_system.service.test.js
  test/translators/authorised_system.translator.test.js
Labels: enhancement

#69 Add database health check controller
  app/controllers/admin/health/database.controller.js
  app/controllers/index.js
  app/plugins/router.plugin.js
  app/routes/database.routes.js
  app/routes/index.js
  app/services/database_health_check.service.js
  app/services/index.js
  test/controllers/admin/health/database.controller.test.js
  test/services/database_health_check.service.test.js
Labels: enhancement

#73 Add create bill run service
  app/services/create_bill_run.service.js
  app/services/index.js
  test/services/create_bill_run.service.test.js
Labels: enhancement

#70 Use knex config to handle multiple environments
  .env.example
  .github/workflows/ci.yml
  config/database.config.js
  db/create_database.js
  db/index.js
  knexfile.js
  package.json
Labels: housekeeping

#74 Update bill runs ctrlr. to use new functionality
  app/controllers/base_bill_runs.controller.js
  app/controllers/index.js
  app/controllers/presroc/bill_runs.controller.js
  app/routes/bill_run.routes.js
  test/controllers/presroc/bill_runs.controller.test.js
Labels: enhancement

#75 Add not-supported controller to project
  app/controllers/index.js
  app/controllers/not_supported.controller.js
  app/routes/bill_run.routes.js
  test/controllers/not_supported.controller.test.js
  test/support/helpers/route.helper.js
Labels: enhancement

#76 Pre-update the transactions controllers
  app/controllers/base_transactions.controller.js
  app/controllers/index.js
  app/controllers/presroc/transactions.controller.js
  app/controllers/sroc/transactions.controller.js
  app/routes/transaction.routes.js
Labels: housekeeping

#79 Create transaction model
  app/models/bill_run.model.js
  app/models/transaction.model.js
  db/migrations/20201203144442_create_transactions.js
Labels: enhancement

#80 Create add transaction endpoint
  app/controllers/index.js
  app/controllers/presroc/add_bill_run_transaction.controller.js
  app/routes/bill_run.routes.js
  test/controllers/presroc/add_bill_run_transaction.controller.test.js
  test/controllers/presroc/bill_runs.controller.test.js
Labels: enhancement

#82 Make docker dev environment more distinct
  docker-compose.yml
Labels: housekeeping

#83 Automatically parse DB bigints as JavaScript Ints
  db/index.js
Labels: enhancement

#78 Add pre-sroc transaction translator
  app/translators/index.js
  app/translators/transaction.translator.js
  test/translators/transaction.translator.test.js
Labels: enhancement

#85 Fix sonarcloud smell - return regimes directly
  app/services/create_authorised_system.service.js
Labels: housekeeping

#90 Fix not handling unknown client id
  app/auth/jwt_strategy.auth.js
  test/features/authentication.test.js
Labels: bug

#87 Migrate calculate charge from SROC to PRESROC
  app/controllers/base_calculate_charge.controller.js
  app/controllers/index.js
  app/controllers/presroc/calculate_charge.controller.js
  app/controllers/sroc/calculate_charge.controller.js
  app/models/charge.model.js
  app/models/index.js
  app/presenters/calculate_charge.presenter.js
  app/presenters/charge.presenter.js
  app/presenters/index.js
  app/presenters/rules_service.presenter.js
  app/routes/calculate_charge.routes.js
  app/services/calculate_charge.service.js
  app/services/rules.service.js
  app/translators/calculate_charge.translator.js
  app/translators/index.js
  app/translators/rules_service.translator.js
  app/translators/sroc_charge.translator.js
  test/controllers/calculate_charge.controller.test.js
  test/controllers/presroc/add_bill_run_transaction.controller.test.js
  test/controllers/presroc/calculate_charge.controller.test.js
  test/presenters/calculate_charge.presenter.test.js
  test/presenters/charge.presenter.test.js
  test/services/calculate_charge.service.test.js
  test/services/rules.service.test.js
  test/support/fixtures/calculate_charge/index.js
  test/support/fixtures/calculate_charge/presroc/s126_prorata_credit_request.json
  test/support/fixtures/calculate_charge/presroc/s126_prorata_credit_response.json
  test/support/fixtures/calculate_charge/presroc/s126_prorata_credit_rules_service.json
  test/support/fixtures/calculate_charge/presroc/section_agreements_true_request.json
  test/support/fixtures/calculate_charge/presroc/section_agreements_true_response.json
  test/support/fixtures/calculate_charge/presroc/section_agreements_true_rules_service.json
  test/support/fixtures/calculate_charge/presroc/simple_request.json
  test/support/fixtures/calculate_charge/presroc/simple_response.json
  test/support/fixtures/calculate_charge/presroc/simple_rules_service.json
  test/support/fixtures/charge.json
  test/support/fixtures/wrls/calculate_charge/calculate_charge_request_s126_prorata_credit.json
  test/support/fixtures/wrls/calculate_charge/calculate_charge_request_s127_s130.json
  test/support/fixtures/wrls/calculate_charge/calculate_charge_request_simple.json
  test/support/fixtures/wrls/calculate_charge/calculate_charge_response_s126_prorata_credit.json
  test/support/fixtures/wrls/calculate_charge/calculate_charge_response_s127_s130.json
  test/support/fixtures/wrls/calculate_charge/calculate_charge_response_simple.json
  test/support/fixtures/wrls/calculate_charge/index.js
  test/support/fixtures/wrls/calculate_charge/rules_service_request_s126_prorata_credit.json
  test/support/fixtures/wrls/calculate_charge/rules_service_request_s127_s130.json
  test/support/fixtures/wrls/calculate_charge/rules_service_request_simple.json
  test/support/fixtures/wrls/calculate_charge/rules_service_response_s126_prorata_credit.json
  test/support/fixtures/wrls/calculate_charge/rules_service_response_s127_s130.json
  test/support/fixtures/wrls/calculate_charge/rules_service_response_simple.json
  test/support/fixtures/wrls/rules_service_request.json
  test/support/fixtures/wrls/rules_service_response.json
  test/support/helpers/general.helper.js
  test/support/helpers/index.js
  test/support/helpers/rules_service.helper.js
  test/translators/calculate_charge.translator.test.js
  test/translators/rules_service.translator.test.js
  test/translators/sroc_charge.translator.test.js
Labels: housekeeping

#92 Only allow 'active' authorised systems
  app/auth/jwt_strategy.auth.js
  app/models/authorised_system.model.js
  test/features/authorisation.test.js
  test/models/authorised_system.model.test.js
  test/support/helpers/authorised_system.helper.js
Labels: enhancement

#91 Create sequence counters
  app/models/index.js
  app/models/regime.model.js
  app/models/sequence_counter.model.js
  app/services/index.js
  app/services/next_bill_run_number.service.js
  db/migrations/20201210145745_alter_bill_runs.js
  db/migrations/20201210151025_create_sequence_counters.js
  db/seeds/03_sequence_counters.js
  test/services/next_bill_run_number.service.test.js
  test/support/helpers/index.js
  test/support/helpers/sequence_counter.helper.js
Labels: enhancement

#94 Add bill run number to create bill run
  app/services/create_bill_run.service.js
  db/migrations/20201215095327_alter_bill_runs.js
  test/controllers/presroc/bill_runs.controller.test.js
  test/services/create_bill_run.service.test.js
Labels: enhancement

#95 Fix reliance on dev-only dependencies in prod.
  config/server.config.js
  server.js
Labels: bug

#96 Fix dev dependencies in production - again!
  app/plugins/index.js
Labels: bug

#93 Update PostgreSQl dependence to v12
  .github/workflows/ci.yml
  README.md
  docker-compose.yml
Labels: enhancement

#97 Create Bill Run presenter
  app/presenters/create_bill_run.presenter.js
  app/presenters/index.js
  app/services/create_bill_run.service.js
  test/controllers/presroc/bill_runs.controller.test.js
  test/presenters/create_bill_run.presenter.test.js
  test/services/create_bill_run.service.test.js
Labels: enhancement

#98 Override default hapi router options
  config/server.config.js
  test/features/routing.test.js
Labels: enhancement

#101 Multi-stage docker build
  Dockerfile
  docker-compose.yml
Labels: enhancement

#102 Add --shuffle parameter to lab
  package.json
Labels: enhancement

#103 Fix issue with authorised system migration scripts
  db/migrations/20201127100927_alter_authorised_systems.js
  db/migrations/20201218153444_alter_authorised_systems.js
Labels: bug

#104 Transaction translator
  app/translators/base.translator.js
  app/translators/transaction.translator.js
  test/translators/base.translator.test.js
  test/translators/transaction.translator.test.js
Labels: enhancement

#99 Add alter transaction table migration
  db/migrations/20201217145238_alter_transactions.js
Labels: enhancement

#105 Add stop (SIGTERM) plugin
  app/plugins/index.js
  app/plugins/stop.plugin.js
  server.js
  test/features/graceful_shutdown.test.js
Labels: enhancement

#106 Add create transaction presenter
  app/presenters/create_transaction.presenter.js
  app/presenters/index.js
  test/presenters/create_transaction.presenter.test.js
Labels: enhancement

#108 Allow access to validatedData in translators
  app/translators/base.translator.js
  test/translators/base.translator.test.js
Labels: enhancement

#109 Update transaction model relations
  app/models/authorised_system.model.js
  app/models/index.js
  app/models/regime.model.js
  app/models/transaction.model.js
Labels: housekeeping

#110 Fix charge credit vs credit in transaction
  app/presenters/calculate_charge.presenter.js
  app/translators/calculate_charge.translator.js
  app/translators/transaction.translator.js
  test/presenters/calculate_charge.presenter.test.js
Labels: housekeeping

#111 Fix chargeFinancialYear vs financialYear in trans.
  app/presenters/rules_service.presenter.js
  app/translators/calculate_charge.translator.js
  app/translators/transaction.translator.js
  test/translators/calculate_charge.translator.test.js
Labels: housekeeping

#112 Fix chargePeriodStart vs periodStart in trans.
  app/translators/calculate_charge.translator.js
  app/translators/transaction.translator.js
Labels: housekeeping

#113 Fix chargePeriodEnd vs periodEnd in trans.
  app/translators/calculate_charge.translator.js
  app/translators/transaction.translator.js
Labels: housekeeping

#114 Retain rules service response in translator
  app/translators/rules_service.translator.js
  test/translators/rules_service.translator.test.js
Labels: enhancement

#115 Add default ruleset property to Trans. translator
  app/translators/calculate_charge.translator.js
  app/translators/transaction.translator.js
  test/translators/calculate_charge.translator.test.js
  test/translators/transaction.translator.test.js
Labels: housekeeping

#116 Update Trans. Translator to expect bill run id
  app/translators/transaction.translator.js
  test/translators/transaction.translator.test.js
Labels: housekeeping

#117 Update Trans. Translator to expect Regime Id
  app/translators/transaction.translator.js
  test/translators/transaction.translator.test.js
Labels: housekeeping

#118 Update Trans. Translator to expect Auth. System Id
  app/translators/transaction.translator.js
  test/translators/transaction.translator.test.js
Labels: housekeeping

#120 Update Bill Run Translator to expect Regime Id
  app/services/create_bill_run.service.js
  app/translators/bill_run.translator.js
  test/translators/bill_run.translator.test.js
Labels: housekeeping

#121 Update Bill Run Translator expect Auth. System Id
  app/services/create_bill_run.service.js
  app/translators/bill_run.translator.js
  test/translators/bill_run.translator.test.js
Labels: housekeeping

#122 Revert making _data enumerable in base translator
  app/translators/base.translator.js
Labels: bug

#123 Simplify auth. system creation in service
  app/services/create_authorised_system.service.js
  app/translators/authorised_system.translator.js
  test/translators/authorised_system.translator.test.js
Labels: housekeeping

#125 Update Calculate Charge Translator expect Regime slug
  app/services/calculate_charge.service.js
  app/translators/calculate_charge.translator.js
  test/translators/calculate_charge.translator.test.js
Labels: housekeeping

#126 Access rules service result from charge service
  app/services/calculate_charge.service.js
  test/services/calculate_charge.service.test.js
Labels: housekeeping

#107 Add create transaction service
  app/services/create_transaction.service.js
  app/services/index.js
  test/services/create_transaction.service.test.js
  test/support/fixtures/create_transaction/index.js
  test/support/fixtures/create_transaction/presroc/simple.json
Labels: enhancement

#128 Add missing test coverage 4 RulesServiceTranslator
  app/translators/rules_service.translator.js
  test/translators/rules_service.translator.test.js
Labels: housekeeping

#129 Refactor add bill run transaction controller
  app/controllers/index.js
  app/controllers/presroc/add_bill_run_transaction.controller.js
  app/controllers/presroc/bill_runs.controller.js
  app/routes/bill_run.routes.js
  test/controllers/presroc/add_bill_run_transaction.controller.test.js
  test/controllers/presroc/bill_runs.controller.test.js
Labels: housekeeping

#130 Remove transactions controller
  app/controllers/index.js
  app/controllers/presroc/transactions.controller.js
  app/routes/transaction.routes.js
Labels: housekeeping

#131 Link add transaction endpoint with service
  app/controllers/presroc/bill_runs.controller.js
  test/controllers/presroc/bill_runs.controller.test.js
  test/support/helpers/bill_run.helper.js
  test/support/helpers/index.js
Labels: enhancement

#132 Add default for status in bill run table
  db/migrations/20201224094044_alter_bill_runs.js
Labels: bug

#133 Remove bill run number from transactions
  db/migrations/20201210145745_alter_bill_runs.js
Labels: housekeeping

#134 Add foreign key constraint to bill run id in trans
  db/migrations/20201203144442_create_transactions.js
  test/services/create_transaction.service.test.js
Labels: enhancement
