Repository DEFRA/sroc-charging-module-api, pull requests merged in 2020-11, with the labels that each got.

#37 Add SOP data validation plugin
  app/plugins/index.js
  app/plugins/invalid_characters.plugin.js
  server.js
  test/features/invalid_characters.test.js
Labels: enhancement

#38 Move the existing onRequest hook to a plugin
  app/hooks/index.js
  app/hooks/on_request.hook.js
  app/plugins/index.js
  app/plugins/missing_payload.plugin.js
  server.js
  test/features/reject_missing_payloads.test.js
Labels: housekeeping

#41 Switch to using GitHub Actions for CI
  .github/workflow/ci.yml
  .github/workflows/ci.yml
  .travis.yml
  README.md
  sonar-project.properties
Labels: housekeeping

#45 Add back check for use of `only()` in tests to CI
  .github/workflows/ci.yml
Labels: housekeeping

#39 Move existing onCredentials hook to plugin
  app/hooks/index.js
  app/hooks/on_credentials.hook.js
  app/plugins/authorisation.plugin.js
  app/plugins/index.js
  server.js
  test/features/authorisation.test.js
  test/support/helpers/route.helper.js
Labels: housekeeping

#40 Add custom plugin to handle 'cleaning' payloads
  app/plugins/clean_payload.plugin.js
  app/plugins/index.js
  server.js
  test/features/clean_payloads.test.js
  test/features/sanitise_payloads.test.js
Labels: enhancement

#46 Fix cleanse payload rejecting false booleans
  app/plugins/clean_payload.plugin.js
  test/features/clean_payloads.test.js
Labels: bug

#49 Fix payload plugins for arrays and boolean true
  app/plugins/clean_payload.plugin.js
  app/plugins/disinfect.plugin.js
  app/plugins/index.js
  app/plugins/payload_cleaner.plugin.js
  app/plugins/unescape.plugin.js
  app/services/index.js
  app/services/object_cleaning.service.js
  package-lock.json
  package.json
  server.js
  test/features/clean_payloads.test.js
  test/features/sanitise_payloads.test.js
  test/services/object_cleaning.service.test.js
Labels: bug

#50 Update authorised_systems to use conventional id
  app/auth/jwt_strategy.auth.js
  db/migrations/20201012150934_create_authorised_systems.js
  db/seeds/02_authorised_systems.js
  test/support/helpers/authorised_system.helper.js
Labels: housekeeping

#51 Update seed files to use async / await pattern
  db/seeds/01_regimes.js
  db/seeds/02_authorised_systems.js
Labels: housekeeping

#52 Move regimes endpoint to /admin path
  app/controllers/admin/regimes.controller.js
  app/controllers/index.js
  app/routes/regime.routes.js
Labels: housekeeping

#54 Add new base model class
  app/models/authorised_system.model.js
  app/models/base.model.js
  app/models/index.js
  app/models/regime.model.js
Labels: enhancement

#55 Add many-to-many rel. for Auth. System and Regime
  app/models/authorised_system.model.js
  app/models/regime.model.js
  db/migrations/20201116103729_create_authorised_systems_regimes.js
Labels: enhancement

#58 Change .call() to .go()
  app/auth/jwt_strategy.auth.js
  app/controllers/sroc/calculate_charge.controller.js
  app/plugins/payload_cleaner.plugin.js
  app/presenters/base.presenter.js
  app/services/calculate_charge.service.js
  app/services/cognito_jwt_to_pem.service.js
  app/services/object_cleaning.service.js
  app/services/rules.service.js
  test/presenters/base.presenter.test.js
  test/presenters/charge.presenter.test.js
  test/services/calculate_charge.service.test.js
  test/services/object_cleaning.service.test.js
  test/services/rules.service.test.js
Labels: housekeeping

#59 Underscores in urls? Oh my!
  app/routes/calculate_charge.routes.js
  test/controllers/calculate_charge.controller.test.js
Labels: housekeeping

#57 Implement regime authorisation fully
  app/models/authorised_system.model.js
  app/models/base.model.js
  app/models/charge.model.js
  app/models/regime.model.js
  app/plugins/authorisation.plugin.js
  app/services/authorisation.service.js
  app/services/calculate_charge.service.js
  app/services/cognito_jwt_to_pem.service.js
  app/services/index.js
  app/services/object_cleaning.service.js
  app/services/rules.service.js
  test/features/authorisation.test.js
  test/services/authorisation.service.test.js
  test/support/helpers/authorised_system.helper.js
  test/support/helpers/index.js
  test/support/helpers/regime.helper.js
Labels: enhancement

#60 Implement Docker
  .dockerignore
  Dockerfile
  README.md
  docker-compose.yml
  entrypoint.sh
  makefile
  package.json
Labels: housekeeping

#61 Start using service for regimes index endpoint
  app/controllers/admin/regimes.controller.js
  app/presenters/index.js
  app/presenters/json.presenter.js
  app/services/index.js
  app/services/list_regimes.service.js
  test/controllers/admin/regimes.controller.test.js
  test/presenters/json.presenter.test.js
  test/services/list_regimes.service.test.js
Labels: housekeeping

#65 Make docker Node friendly
  .env.example
  .github/workflows/ci.yml
  .gitignore
  .vscode/tasks.json
  Dockerfile
  README.md
  config/database.config.js
  docker-compose.yml
  entrypoint.sh
  makefile
Labels: bug

#62 Start using service for regimes show endpoint
  app/controllers/admin/regimes.controller.js
  app/services/index.js
  app/services/show_regime.service.js
  test/controllers/admin/regimes.controller.test.js
  test/services/show_regime.service.test.js
Labels: housekeeping
