Repository DEFRA/sroc-charging-module-api, pull requests merged in 2021-09, with the labels that each got.

#527 Add pushing to DockerHub to Docker workflow
  .github/workflows/docker.yml
Labels: housekeeping

#529 Add GitHub actions to Dependabot checks
  .github/dependabot.yml
Labels: housekeeping

#530 Add dev guide amending code to handle new rulesets
  app/README.md
Labels: documentation

#532 Fix automatic push to DockerHub
  .github/workflows/docker.yml
Labels: bug

#534 Fix CSV transform object defect
  app/services/streams/stream_transform_csv.service.js
  test/services/streams/stream_transform_csv.service.test.js
Labels: bug

#533 Fix customer details `null` defect
  app/services/create_customer_details.service.js
  app/translators/customer.translator.js
  test/services/create_customer_details.service.test.js
  test/translators/customer.translator.test.js
Labels: bug

#536 Remove `GET /admin/{regimeId}/customers` endpoint
  app/controllers/admin/customers.controller.js
  app/routes/customer.routes.js
  test/controllers/admin/customers.controller.test.js
Labels: housekeeping

#538 Create `StreamTransformDatRowService`
  app/services/files/transform_records_to_file.service.js
  app/services/index.js
  app/services/streams/stream_transform_dat_row.service.js
  test/services/streams/stream_transform_dat_row.service.test.js
Labels: housekeeping

#537 Amend CSV export format
  app/services/convert_to_csv.service.js
  app/services/files/transform_table_to_file.service.js
  app/services/index.js
  app/services/streams/stream_transform_csv.service.js
  app/services/streams/stream_transform_csv_row.service.js
  test/services/convert_to_csv.service.test.js
  test/services/files/exports/export_table_to_file.service.test.js
  test/services/streams/stream_transform_csv_row.service.test.js
  test/services/streams/stream_writable_file.service.test.js
  test/support/helpers/general.helper.js
Labels: enhancement

#540 Versioning docs
  docs/app.md
  docs/services.md
  docs/versioning.md
Labels: documentation

#541 Reset the Dependabot build fix
  .github/workflows/ci.yml
Labels: bug

#544 Create `DeprecatedRoutePlugin`
  app/plugins/deprecated_route.plugin.js
  app/plugins/index.js
  app/server.js
  test/features/deprecated_route.test.js
  test/support/helpers/route.helper.js
Labels: enhancement

#543 Generate and add unique tag in docker workflow
  .github/workflows/docker.yml
Labels: housekeeping

#545 Fix 2 - issue with unique Docker Tag
  .github/workflows/docker.yml
Labels: bug

#547 Rename show endpoints to view
  app/controllers/admin/authorised_systems.controller.js
  app/controllers/admin/regimes.controller.js
  app/controllers/admin/test/test_customer_files.controller.js
  app/controllers/admin/test/test_transactions.controller.js
  app/routes/authorised_system.routes.js
  app/routes/regime.routes.js
  app/routes/test.routes.js
  app/services/authorised_systems/view_authorised_system.service.js
  app/services/files/customers/view_customer_file.service.js
  app/services/index.js
  app/services/regimes/view_regime.service.js
  app/services/transactions/view_transaction.service.js
  test/controllers/admin/authorised_systems.controller.test.js
  test/controllers/admin/regimes.controller.test.js
  test/controllers/admin/test/test_customer_files.controller.test.js
  test/controllers/admin/test/test_transactions_controller.test.js
  test/services/authorised_systems/view_authorised_system.service.test.js
  test/services/files/customers/view_customer_file.service.test.js
  test/services/regimes/view_regime.service.test.js
  test/services/transactions/view_transaction.service.test.js
Labels: housekeeping

#549 Set up customer files endpoint and dummy service
  app/controllers/admin/test/test_customer_files.controller.js
  app/controllers/customer_files.controller.js
  app/controllers/index.js
  app/plugins/router.plugin.js
  app/routes/customer_files.routes.js
  app/routes/index.js
  app/services/files/customers/list_customer_files.service.js
  app/services/files/customers/test_list_customer_files.service.js
  app/services/index.js
  test/controllers/admin/test/test_customer_files.controller.test.js
  test/controllers/presroc/customer_files.controller.test.js
  test/services/files/customers/list_customer_files.service.test.js
  test/services/files/customers/test_list_customer_files.service.test.js
Labels: enhancement

#554 Implement `ListCustomerFilesService`
  app/controllers/customer_files.controller.js
  app/presenters/index.js
  app/presenters/list_customer_files.presenter.js
  app/services/files/customers/list_customer_files.service.js
  test/controllers/presroc/customer_files.controller.test.js
  test/presenters/list_customer_files.presenter.test.js
  test/services/files/customers/list_customer_files.service.test.js
  test/support/helpers/customer.helper.js
  test/support/helpers/general.helper.js
Labels: enhancement

#555 List customer files controller and route
  app/controllers/customer_files.controller.js
  app/routes/customer_files.routes.js
  app/server.js
  test/controllers/presroc/customer_files.controller.test.js
Labels: enhancement

#556 Amend 0 days parameter with `ListCustomerFilesController`
  app/routes/customer_files.routes.js
  test/controllers/presroc/customer_files.controller.test.js
Labels: enhancement

#558 Expand info returned in customer-files endpoint
  app/presenters/list_customer_files.presenter.js
  app/services/files/customers/list_customer_files.service.js
  test/presenters/list_customer_files.presenter.test.js
Labels: enhancement

#557 Fix customer file head invalid date format
  .nvmrc
  app/presenters/base.presenter.js
  test/presenters/base.presenter.test.js
Labels: bug

#559 Delete Licence not updating bill run status
  app/controllers/bill_runs_licences.controller.js
  app/services/licences/delete_licence.service.js
  test/services/licences/delete_licence.service.test.js
Labels: housekeeping

#562 Fix `ListCustomerFilesService` time boundary defect
  app/services/files/customers/list_customer_files.service.js
  test/services/files/customers/list_customer_files.service.test.js
  test/support/helpers/general.helper.js
Labels: bug

#561 Fix deleting a deminimis invoice recalculation
  app/services/invoices/delete_invoice.service.js
  test/services/invoices/delete_invoice.service.test.js
Labels: bug

#565 Move controller tests out of `presroc` folder
  test/controllers/bill_runs.controller.test.js
  test/controllers/bill_runs_invoices.controller.test.js
  test/controllers/bill_runs_licences.controller.test.js
  test/controllers/bill_runs_transactions.controller.test.js
  test/controllers/calculate_charge.controller.test.js
  test/controllers/customer_details.controller.test.js
  test/controllers/customer_files.controller.test.js
Labels: housekeeping

#566 Fix incorrect `ValidateBillRunLicenceService` parameter issue
  app/controllers/bill_runs_licences.controller.js
  test/controllers/bill_runs_licences.controller.test.js
Labels: bug

#567 Fix deleting a zero value invoice recalculation
  app/services/invoices/delete_invoice.service.js
  test/services/invoices/delete_invoice.service.test.js
Labels: bug

#570 Update test bill run generator with trans. multiplier
  test/controllers/admin/test/test_bill_runs.controller.test.js
  test/support/generators/bill_run.generator.js
Labels: enhancement
