Repository DEFRA/sroc-charging-module-api, pull requests merged in 2021-04, with the labels that each got.

#334 Create initial Generate Customer File Service
  app/services/generate_customer_file.service.js
  app/services/index.js
  test/services/generate_customer_file.service.test.js
Labels: enhancement

#337 Revert Dependabot SonarCloud workaround
  .github/workflows/ci.yml
Labels: housekeeping

#338 Switch to using Notifier plugin
  app/controllers/admin/test/test_bill_runs.controller.js
  app/controllers/presroc/bill_runs.controller.js
  app/services/generate_bill_run.service.js
  app/services/send_transaction_file.service.js
  test/services/generate_bill_run.service.test.js
  test/services/send_transaction_file.service.test.js
  test/support/generators/bill_run.generator.js
Labels: housekeeping

#339 Add Hapi request ID to Notifier
  app/lib/notifier.js
  app/plugins/notifier.plugin.js
  test/lib/notifier.test.js
Labels: enhancement

#341 Simplify the VSCode tasks
  .vscode/tasks.json
  README.md
Labels: housekeeping

#343 Fix - Move delete bill run to background task
  app/controllers/presroc/bill_runs.controller.js
  app/models/bill_run.model.js
  app/services/delete_bill_run.service.js
  test/services/delete_bill_run.service.test.js
Labels: bug

#344 Move test sleep() method to GeneralHelper
  test/controllers/admin/test/test_bill_runs.controller.test.js
  test/support/helpers/general.helper.js
Labels: housekeeping

#345 Fix - Move delete invoice to background task
  app/controllers/presroc/bill_runs_invoices.controller.js
Labels: bug

#342 Next Customer File Reference Service
  app/services/base_next_file_reference.service.js
  app/services/index.js
  app/services/next_customer_file_reference.service.js
  app/services/next_transaction_file_reference.service.js
  app/services/send_bill_run_reference.service.js
  db/migrations/20210407142349_alter_sequence_counters.js
  test/services/base_next_file_reference.service.test.js
  test/services/next_customer_file_reference.service.test.js
  test/services/next_transaction_file_reference.service.test.js
Labels: enhancement

#349 Send Customer File admin endpoint
  app/controllers/admin/customers.controller.js
  app/controllers/index.js
  app/lib/index.js
  app/lib/static_lookup.js
  app/plugins/router.plugin.js
  app/routes/customer.routes.js
  app/routes/index.js
  app/services/index.js
  app/services/send_customer_file.service.js
  test/controllers/admin/customers.controller.test.js
Labels: enhancement

#346 Create Send Customer File Service
  app/services/send_customer_file.service.js
  test/services/send_customer_file.service.test.js
Labels: enhancement

#348 Use customer file presenters
  app/services/generate_customer_file.service.js
  app/services/generate_transaction_file.service.js
  test/services/generate_customer_file.service.test.js
  test/services/generate_transaction_file.service.test.js
Labels: enhancement

#350 Generate customer files when sending bill runs
  app/controllers/presroc/bill_runs.controller.js
  test/controllers/presroc/bill_runs.controller.test.js
Labels: enhancement

#352 Pass correct params to GenerateCustomerFileService
  app/services/send_customer_file.service.js
  test/services/send_customer_file.service.test.js
Labels: bug

#353 Exclude zero value transactions from transaction files
  app/services/generate_transaction_file.service.js
  test/services/generate_transaction_file.service.test.js
Labels: bug

#354 Customer file is sorted by customer reference
  app/services/generate_customer_file.service.js
  test/services/generate_customer_file.service.test.js
Labels: enhancement

#356 Delete invoice error handling
  app/controllers/presroc/bill_runs_invoices.controller.js
  app/services/delete_invoice.service.js
  test/controllers/presroc/bill_runs_invoices.controller.test.js
  test/services/delete_invoice.service.test.js
Labels: bug

#357 Delete bill run error handling
  app/controllers/presroc/bill_runs.controller.js
  app/services/delete_bill_run.service.js
  app/services/delete_invoice.service.js
  app/services/send_customer_file.service.js
  app/services/send_transaction_file.service.js
  test/services/delete_bill_run.service.test.js
Labels: housekeeping

#355 Overwrite existing customer details entry
  app/services/create_customer_details.service.js
  db/migrations/20210413154851_alter_customers.js
  test/services/create_customer_details.service.test.js
  test/services/send_customer_file.service.test.js
Labels: enhancement

#360 Fix transaction file compensation charge defect
  app/presenters/transaction_file_body.presenter.js
  app/services/generate_transaction_file.service.js
  test/presenters/transaction_file_body.presenter.test.js
Labels: bug

#362 Fix transaction file minimum charge defect
  app/presenters/transaction_file_body.presenter.js
  test/presenters/transaction_file_body.presenter.test.js
Labels: bug

#364 Create customer files table
  db/migrations/20210416132011_create_customer_files.js
Labels: enhancement

#365 Link customers table to customer_files
  db/migrations/20210416143924_alter_customers.js
Labels: enhancement

#368 Fix multiple region customer file generation
  app/services/send_customer_file.service.js
  test/services/send_customer_file.service.test.js
Labels: bug

#369 Create exported_customers table
  db/migrations/20210420141638_create_exported_customers.js
Labels: enhancement

#372 Fix POST /customer-changes response code
  app/controllers/presroc/customer_details.controller.js
  test/controllers/presroc/customer_details.controller.test.js
Labels: bug

#373 Fix SendCustomerFileService error logging
  app/services/send_customer_file.service.js
  test/services/send_customer_file.service.test.js
Labels: bug

#374 Initial Invoice Rebilling endpoint
  app/controllers/presroc/bill_runs_invoices.controller.js
  app/routes/bill_run_invoice.routes.js
  test/controllers/presroc/bill_runs_invoices.controller.test.js
Labels: housekeeping

#371 Add customer file to customer_file table
  app/models/index.js
  app/services/send_customer_file.service.js
  db/migrations/20210421110628_alter_customer_files.js
  test/services/send_customer_file.service.test.js
Labels: enhancement

#375 Admin customer changes dummy endpoint
  app/controllers/admin/customers.controller.js
  app/routes/customer.routes.js
  test/controllers/admin/customers.controller.test.js
Labels: enhancement

#380 Fix - add client ID back into conflict response
  app/services/db_errors.service.js
  test/services/db_errors.service.test.js
Labels: bug

#382 Move Customers To Exported Table service
  app/models/exported_customer.model.js
  app/models/index.js
  app/services/index.js
  app/services/move_customers_to_exported_table.service.js
  test/services/move_customers_to_exported_table.service.test.js
Labels: enhancement

#370 Add generate customer file task
  app/tasks/customer_files.task.js
  app/tasks/index.js
  app/tasks/task_runner.js
  package.json
  test/tasks/customer_files.task.test.js
  test/tasks/task_runner.test.js
Labels: enhancement

#379 Add TaskNotifier and refactor existing Notifier
  app/controllers/admin/health/airbrake.controller.js
  app/lib/base_notifier.js
  app/lib/index.js
  app/lib/notifier.js
  app/lib/request_notifier.js
  app/lib/task_notifier.js
  app/plugins/airbrake.plugin.js
  app/plugins/index.js
  app/plugins/request_notifier.plugin.js
  app/services/delete_bill_run.service.js
  app/services/delete_invoice.service.js
  app/services/generate_bill_run.service.js
  app/services/send_customer_file.service.js
  app/services/send_transaction_file.service.js
  server.js
  test/features/add_notifier_to_requests.test.js
  test/lib/base_notifier.test.js
  test/lib/notifier.test.js
  test/lib/request_notifier.test.js
  test/lib/task_notifier.test.js
Labels: enhancement

#383 Update TaskRunner to use TaskNotifier
  app/tasks/task_runner.js
Labels: housekeeping

#384 Send Customer File Service moves customers to exported_customers
  app/services/send_customer_file.service.js
  test/services/move_customers_to_exported_table.service.test.js
  test/services/send_customer_file.service.test.js
Labels: enhancement

#381 Add customer files test endpoint
  app/controllers/admin/test/test_customer_files.controller.js
  app/controllers/index.js
  app/routes/test.routes.js
  app/services/index.js
  app/services/list_customer_files.service.js
  test/controllers/admin/test/test_customer_files.controller.test.js
  test/services/list_customer_files.service.test.js
  test/support/helpers/customer.helper.js
  test/support/helpers/index.js
Labels: enhancement

#386 Fix previous changes in customer file export
  app/services/generate_customer_file.service.js
  app/services/send_customer_file.service.js
  test/services/generate_customer_file.service.test.js
  test/services/send_customer_file.service.test.js
Labels: bug

#385 Add test Show customer file endpoint
  app/controllers/admin/test/test_customer_files.controller.js
  app/models/customer_file.model.js
  app/models/exported_customer.model.js
  app/models/sequence_counter.model.js
  app/routes/test.routes.js
  app/services/index.js
  app/services/show_customer_file.service.js
  test/controllers/admin/test/test_customer_files.controller.test.js
  test/services/show_customer_file.service.test.js
  test/support/helpers/customer.helper.js
Labels: enhancement

#388 Use consistent naming convention package scripts
  .github/workflows/ci.yml
  .vscode/tasks.json
  package.json
Labels: housekeeping

#391 Fix jwk file selection for INTEGRATION
  keys/tra.jwk.json
Labels: bug

#389 Move plugin based services to own folder
  app/services/index.js
  app/services/plugins/db_errors.service.js
  app/services/plugins/object_cleaning.service.js
  app/services/plugins/request_bill_run.service.js
Labels: housekeeping

#390 Move JwtStrategyAuth to app/lib folder
  app/auth/index.js
  app/lib/index.js
  app/lib/jwt_strategy.js
  server.js
Labels: housekeeping

#392 Fix failing MoveCustomersToExportedTableService tests
  test/services/move_customers_to_exported_table.service.test.js
Labels: bug

#394 Move plugin test files to plugins folder
  test/services/plugins/db_errors.service.test.js
  test/services/plugins/object_cleaning.service.test.js
  test/services/plugins/request_bill_run.service.test.js
Labels: housekeeping

#393 Create plugin to add invoice to request when needed
  app/plugins/index.js
  app/plugins/request_invoice.plugin.js
  app/services/index.js
  app/services/plugins/request_invoice.service.js
  server.js
  test/controllers/presroc/bill_runs_invoices.controller.test.js
  test/features/find_validate_invoices.test.js
  test/services/plugins/request_invoice.service.test.js
  test/support/helpers/route.helper.js
Labels: housekeeping
