Repository DEFRA/sroc-charging-module-api, pull requests merged in 2021-12, with the labels that each got.

#624 View SRoC Bill Run and v3 route
  app/presenters/view_bill_run.presenter.js
  app/presenters/view_bill_run_invoice.presenter.js
  app/routes/bill_run.routes.js
  app/services/bill_runs/view_bill_run.service.js
  test/controllers/bill_runs.controller.test.js
  test/presenters/view_bill_run.presenter.test.js
  test/services/bill_runs/view_bill_run.service.test.js
Labels: enhancement

#630 Fix invoice flags not correctly reflecting state change
  app/services/bill_runs/generate_bill_run.service.js
  test/services/bill_runs/generate_bill_run.service.test.js
Labels: bug

#629 View SRoC Invoice and v3 route
  app/presenters/view_invoice.presenter.js
  app/presenters/view_licence.presenter.js
  app/presenters/view_transaction.presenter.js
  app/routes/bill_run_invoice.routes.js
  app/services/invoices/view_invoice.service.js
  test/controllers/bill_runs_invoices.controller.test.js
  test/presenters/view_invoice.presenter.test.js
  test/presenters/view_transaction.presenter.test.js
  test/services/invoices/view_invoice.service.test.js
Labels: enhancement

#631 Add Swagger request versioning to docs
  docs/versioning.md
Labels: documentation

#632 Amend send bill run statuses
  app/models/bill_run.model.js
  app/services/bill_runs/send_bill_run_reference.service.js
  app/services/files/transactions/send_transaction_file.service.js
  test/services/bill_runs/send_bill_run_reference.service.test.js
  test/services/files/transactions/send_transaction_file.service.test.js
Labels: enhancement

#633 CMEA-226 Make use of pending status consistent
  app/models/bill_run.model.js
  app/services/bill_runs/delete_bill_run.service.js
  app/services/bill_runs/generate_bill_run.service.js
  app/services/bill_runs/generate_bill_run_validation.service.js
  test/models/bill_run.model.test.js
  test/services/bill_runs/delete_bill_run.service.test.js
  test/services/bill_runs/generate_bill_run.service.test.js
  test/services/bill_runs/generate_bill_run_validation.service.test.js
Labels: housekeeping

#634 CMEA-232 Add new V3 delete invoice endpoint
  app/routes/bill_run_invoice.routes.js
  test/controllers/bill_runs_invoices.controller.test.js
Labels: enhancement
