Repository DEFRA/sroc-charging-module-api, pull requests merged in 2021-03, with the labels that each got.

#246 Connect Delete Invoice Service to controller
  app/controllers/presroc/bill_runs_invoices.controller.js
  test/controllers/presroc/bill_runs_invoices.controller.test.js
Labels: enhancement

#244 Hook up view bill run invoice endpoint to service
  app/controllers/presroc/bill_runs_invoices.controller.js
  test/controllers/presroc/bill_runs_invoices.controller.test.js
Labels: enhancement

#250 CalculateChargeTranslator title case fix for two-word strings
  app/translators/calculate_charge.translator.js
  test/translators/calculate_charge.translator.test.js
Labels: bug

#251 Remove approvedForBilling from view bill run
  app/presenters/view_bill_run.presenter.js
Labels: housekeeping

#252 Update bill run status when last invoice is deleted
  app/models/bill_run.model.js
  app/services/delete_invoice.service.js
  test/services/delete_invoice.service.test.js
Labels: enhancement

#253 Remove bill run fetch and checks in BillRunService
  app/controllers/admin/test/test_bill_runs.controller.js
  app/controllers/presroc/bill_runs_transactions.controller.js
  app/services/bill_run.service.js
  app/services/create_transaction.service.js
  test/controllers/presroc/bill_runs.controller.test.js
  test/services/bill_run.service.test.js
  test/services/calculate_minimum_charge.service.test.js
  test/services/create_minimum_charge_adjustment.service.test.js
  test/services/create_transaction.service.test.js
  test/services/delete_invoice.service.test.js
  test/services/generate_bill_run.service.test.js
  test/services/show_transaction.service.test.js
  test/services/view_bill_run.service.test.js
  test/support/generators/bill_run.generator.js
Labels: housekeeping

#256 Add signedChargeValue to ShowTransactionService
  app/services/show_transaction.service.js
  test/services/show_transaction.service.test.js
Labels: enhancement

#255 Create customers table
  db/migrations/20210302125559_create_customers.js
Labels: enhancement

#254 Add CreateTransactionTallyPatchService
  app/services/create_transaction_tally.service.js
  app/services/index.js
  test/services/create_transaction_tally.service.test.js
Labels: housekeeping

#260 Handle call to /generate for generated bill run
  app/services/generate_bill_run_validation.service.js
  test/services/generate_bill_run_validation.service.test.js
Labels: enhancement

#259 Rename & refactor bill run service to use patch
  app/services/bill_run.service.js
  app/services/create_transaction.service.js
  app/services/create_transaction_bill_run.service.js
  app/services/index.js
  test/services/bill_run.service.test.js
  test/services/create_transaction_bill_run.service.test.js
Labels: housekeeping

#261 Rename & refactor invoice service to use patch
  app/services/create_transaction.service.js
  app/services/create_transaction_invoice.service.js
  app/services/index.js
  app/services/invoice.service.js
  test/services/create_transaction_invoice.service.test.js
  test/services/invoice.service.test.js
Labels: housekeeping

#262 Create Customer Details service
  app/models/customer.model.js
  app/models/index.js
  app/services/create_customer_details.service.js
  app/services/index.js
  app/translators/customer.translator.js
  app/translators/index.js
  test/services/create_customer_details.service.test.js
Labels: enhancement

#263 Rename & refactor licence service to use patch
  app/services/create_transaction.service.js
  app/services/create_transaction_licence.service.js
  app/services/index.js
  app/services/licence.service.js
  test/services/create_transaction_licence.service.test.js
  test/services/licence.service.test.js
Labels: housekeeping

#266 Customer Details controller and endpoint
  app/controllers/index.js
  app/controllers/presroc/customer_details.controller.js
  app/plugins/router.plugin.js
  app/routes/customer_details.routes.js
  app/routes/index.js
  app/services/create_customer_details.service.js
  test/controllers/presroc/customer_details.controller.test.js
Labels: enhancement

#267 Initial Delete Bill Run endpoint
  app/controllers/presroc/bill_runs.controller.js
  app/routes/bill_run.routes.js
  test/controllers/presroc/bill_runs.controller.test.js
Labels: enhancement

#269 Link invoices table to bill_runs table
  db/migrations/20210304172629_alter_invoices.js
  test/models/invoice.model.test.js
  test/services/create_transaction_bill_run.service.test.js
  test/services/create_transaction_invoice.service.test.js
  test/services/create_transaction_licence.service.test.js
Labels: enhancement

#265 Add NextTransactionReferenceService and migration
  app/services/index.js
  app/services/next_transaction_reference.service.js
  db/migrations/20210304112943_alter_sequence_counters.js
  test/services/next_transaction_reference.service.test.js
Labels: enhancement

#264 Limit create transaction returning() fields
  app/services/create_transaction.service.js
Labels: housekeeping

#270 Add NextFileReferenceService and migration
  app/services/index.js
  app/services/next_file_reference.service.js
  config/rules_service.config.js
  db/migrations/20210304235307_alter_sequence_counters.js
  test/services/next_file_reference.service.test.js
Labels: enhancement

#272 Add SendBillRunReferenceService
  app/models/bill_run.model.js
  app/models/invoice.model.js
  app/services/index.js
  app/services/next_file_reference.service.js
  app/services/next_transaction_reference.service.js
  app/services/send_bill_run_reference.service.js
  db/migrations/20210305132500_alter_bill_runs.js
  test/models/bill_run.model.test.js
  test/models/invoice.model.test.js
  test/services/send_bill_run_reference.service.test.js
  test/support/helpers/invoice.helper.js
Labels: enhancement

#275 Hook up /send bill run endpoint to new service
  app/controllers/presroc/bill_runs.controller.js
  test/controllers/presroc/bill_runs.controller.test.js
Labels: enhancement

#268 Delete Bill Run service
  app/models/bill_run.model.js
  app/services/delete_bill_run.service.js
  app/services/index.js
  db/migrations/20201203144442_create_transactions.js
  test/services/delete_bill_run.service.test.js
Labels: enhancement

#273 Fix deminimis invoices being included in bill run figures
  app/services/generate_bill_run.service.js
  test/services/generate_bill_run.service.test.js
Labels: bug

#276 Bill run summary net zero value fix
  app/models/invoice.model.js
  test/services/generate_bill_run.service.test.js
Labels: bug

#278 Update the view bill run response
  app/presenters/view_bill_run.presenter.js
  app/services/view_bill_run.service.js
  test/services/view_bill_run.service.test.js
Labels: housekeeping

#279 Connect Delete Bill Run service to endpoint
  app/controllers/presroc/bill_runs.controller.js
  app/services/delete_bill_run.service.js
  test/controllers/presroc/bill_runs.controller.test.js
  test/services/delete_bill_run.service.test.js
Labels: enhancement

#281 Fix incorrect values on minimum charge transaction
  app/services/create_minimum_charge_adjustment.service.js
  test/services/create_minimum_charge_adjustment.service.test.js
Labels: bug

#282 Revise BillRunModel.$netTotal() to exclude deminimis
  app/models/bill_run.model.js
  app/services/view_bill_run.service.js
  test/services/view_bill_run.service.test.js
Labels: bug

#284 Initial Generate Transaction File Service
  .dockerignore
  app/services/generate_transaction_file.service.js
  app/services/index.js
  config/server.config.js
  package-lock.json
  package.json
  test/services/generate_transaction_file.service.test.js
  tmp/.keep
Labels: enhancement

#285 Add transaction type to test GET endpoint
  app/services/show_transaction.service.js
  test/services/show_transaction.service.test.js
Labels: enhancement

#287 Fix MaxListenersExceededWarning in tests
  app/plugins/stop.plugin.js
Labels: housekeeping

#288 Housekeeping - Remove stray console.log() calls
  app/controllers/presroc/customer_details.controller.js
  test/models/invoice.model.test.js
Labels: housekeeping

#291 Add more data overrides to test LicenceHelper
  test/support/helpers/licence.helper.js
Labels: enhancement

#292 Fix no SONAR_TOKEN for dependabot PR's
  .github/workflows/ci.yml
Labels: bug, housekeeping

#295 Update CreateTransactionTallyService for UPSERT
  app/services/create_transaction_bill_run.service.js
  app/services/create_transaction_invoice.service.js
  app/services/create_transaction_licence.service.js
  app/services/create_transaction_tally.service.js
  test/services/create_transaction_tally.service.test.js
Labels: enhancement

#293 Send File To S3 service
  .env.example
  .labrc.js
  app/services/index.js
  app/services/send_file_to_s3.service.js
  config/index.js
  config/s3.config.js
  config/server.config.js
  package-lock.json
  package.json
  test/services/send_file_to_s3.service.test.js
Labels: enhancement

#300 Attempt to fix vulnerabilities in package.json
  .vscode/tasks.json
  app/services/request_bill_run.service.js
  package-lock.json
  package.json
Labels: housekeeping

#297 Add CreateTransactionBillRunValidationService
  app/controllers/presroc/bill_runs_transactions.controller.js
  app/services/create_transaction_bill_run.service.js
  app/services/create_transaction_bill_run_validation.service.js
  app/services/index.js
  test/controllers/presroc/bill_runs_transactions.controller.test.js
  test/services/create_transaction_bill_run.service.test.js
  test/services/create_transaction_bill_run_validation.service.test.js
Labels: enhancement

#294 Add base model that provides UPSERT support
  app/models/base_upsert.model.js
  app/models/invoice.model.js
  app/models/licence.model.js
  test/models/base_upsert.model.test.js
  test/models/invoice.model.test.js
  test/models/licence.model.test.js
Labels: enhancement

#298 Switch licence update in CreateTransactionService
  app/services/create_transaction.service.js
  app/services/create_transaction_licence.service.js
  app/services/index.js
  test/services/create_transaction_licence.service.test.js
Labels: enhancement, on hold

#299 Switch invoice update in CreateTransactionService
  app/services/create_transaction.service.js
  app/services/create_transaction_invoice.service.js
  app/services/index.js
  test/services/create_transaction_invoice.service.test.js
Labels: enhancement

#304 Refactor update bill run when creating transaction
  app/models/bill_run.model.js
  app/services/create_transaction.service.js
  app/services/create_transaction_bill_run.service.js
  app/services/index.js
  test/models/bill_run.model.test.js
  test/services/create_transaction_bill_run.service.test.js
Labels: housekeeping

#305 Remove redundant base model query and code
  app/models/base.model.js
  app/models/base_query_builder.js
Labels: housekeeping

#306 Remove 'tally' fields from responses
  app/presenters/view_invoice.presenter.js
  app/presenters/view_licence.presenter.js
  app/services/view_bill_run.service.js
  app/services/view_bill_run_invoice.service.js
  test/services/view_bill_run_invoice.service.test.js
Labels: housekeeping

#307 Add trans. reference to invoice in VIEW bill run
  app/services/view_bill_run.service.js
Labels: enhancement

#308 Send Transaction File Service
  app/models/bill_run.model.js
  app/services/generate_transaction_file.service.js
  app/services/index.js
  app/services/send_file_to_s3.service.js
  app/services/send_transaction_file.service.js
  test/services/send_transaction_file.service.test.js
Labels: enhancement

#309 Add SendTransactionFileService to bill run send controller
  app/controllers/presroc/bill_runs.controller.js
  app/services/index.js
  test/controllers/presroc/bill_runs.controller.test.js
Labels: enhancement

#312 Fix send bill run link to generate file issue
  app/controllers/presroc/bill_runs.controller.js
  app/services/send_bill_run_reference.service.js
  app/services/send_file_to_s3.service.js
  app/services/send_transaction_file.service.js
  test/services/send_bill_run_reference.service.test.js
  test/services/send_file_to_s3.service.test.js
Labels: bug

#311 Fix Docker local permissions and bump Node version
  Dockerfile
Labels: housekeeping

#313 Remove tally fields from invoices in view bill run
  app/presenters/index.js
  app/presenters/view_bill_run.presenter.js
  app/presenters/view_bill_run_invoice.presenter.js
  test/presenters/view_bill.presenter.test.js
Labels: housekeeping

#316 Create DeleteFileService
  app/services/delete_file.service.js
  app/services/index.js
  test/services/delete_file.service.test.js
Labels: enhancement

#314 Add new docker helpers for local development
  .vscode/tasks.json
  db/migrations/20210215154015_alter_transactions_and_invoices.js
  package.json
Labels: housekeeping

#320 Add --no-cache arg to DockerHub build
  hooks/build
Labels: housekeeping

#318 Remove 'tmp' folder from project
  tmp/.keep
Labels: housekeeping

#319 Fix installing react-native as a dependency
  .github/workflows/ci.yml
  Dockerfile
Labels: bug

#322 Add credit and debit line values back to invoices
  app/presenters/view_bill_run_invoice.presenter.js
  app/presenters/view_invoice.presenter.js
  test/presenters/view_bill.presenter.test.js
  test/presenters/view_invoice.presenter.test.js
Labels: enhancement

#315 SendTransactionFileService error handling
  app/services/delete_file.service.js
  app/services/generate_transaction_file.service.js
  app/services/send_file_to_s3.service.js
  app/services/send_transaction_file.service.js
  test/services/delete_file.service.test.js
  test/services/generate_transaction_file.service.test.js
  test/services/send_file_to_s3.service.test.js
  test/services/send_transaction_file.service.test.js
Labels: enhancement

#323 Fix unique error messages in Send Trans. file
  app/services/send_transaction_file.service.js
  test/services/send_transaction_file.service.test.js
Labels: housekeeping

#326 Fix 500 error for empty region in POST transaction
  .nvmrc
  app/services/create_transaction_bill_run_validation.service.js
  test/services/create_transaction_bill_run_validation.service.test.js
Labels: bug

#324 Add new Notifier plugin
  app/lib/index.js
  app/lib/notifier.js
  app/plugins/index.js
  app/plugins/notifier.plugin.js
  server.js
  test/features/add_notifier_to_requests.test.js
  test/lib/notifier.test.js
  test/support/helpers/route.helper.js
Labels: enhancement

#327 Implement stream services for generating transaction files
  app/services/index.js
  app/services/streams/stream_readable_data.service.js
  app/services/streams/stream_readable_records.service.js
  app/services/streams/stream_transform_csv.service.js
  app/services/streams/stream_transform_using_presenter.service.js
  app/services/streams/stream_writable_file.service.js
  package-lock.json
  package.json
  test/services/streams/stream_readable_data.service.test.js
  test/services/streams/stream_readable_records.service.test.js
  test/services/streams/stream_transform_csv.service.test.js
  test/services/streams/stream_transform_using_presenter.service.test.js
  test/services/streams/stream_writable_file.service.js
  test/support/helpers/index.js
  test/support/helpers/stream.helper.js
Labels: enhancement

#328 Presenters for writing transaction file
  app/presenters/base.presenter.js
  app/presenters/index.js
  app/presenters/transaction_file_body.presenter.js
  app/presenters/transaction_file_head.presenter.js
  app/presenters/transaction_file_tail.presenter.js
  test/presenters/base.presenter.test.js
  test/presenters/transaction_file_body.presenter.test.js
  test/presenters/transaction_file_header.presenter.test.js
  test/presenters/transaction_file_tail.presenter.test.js
Labels: enhancement

#330 Transform Records to File service
  app/services/index.js
  app/services/transform_records_to_file.service.js
  test/services/transform_records_to_file.service.test.js
Labels: enhancement

#331 Update Generate Transaction File service
  app/presenters/base.presenter.js
  app/presenters/transaction_file_body.presenter.js
  app/presenters/transaction_file_head.presenter.js
  app/presenters/transaction_file_tail.presenter.js
  app/services/generate_transaction_file.service.js
  app/services/send_transaction_file.service.js
  app/services/streams/stream_readable_records.service.js
  app/services/transform_records_to_file.service.js
  test/presenters/base.presenter.test.js
  test/presenters/transaction_file_body.presenter.test.js
  test/presenters/transaction_file_head.presenter.test.js
  test/presenters/transaction_file_tail.presenter.test.js
  test/services/generate_transaction_file.service.test.js
  test/services/send_transaction_file.service.test.js
  test/services/streams/stream_readable_records.service.test.js
  test/services/transform_records_to_file.service.test.js
Labels: enhancement
