Repository DEFRA/sroc-charging-module-api, pull requests merged in 2021-02, with the labels that each got.

#172 Add Database error plugin
  app/plugins/db_errors.plugin.js
  app/plugins/index.js
  app/services/db_errors.service.js
  app/services/index.js
  server.js
  test/controllers/presroc/bill_runs.controller.test.js
  test/services/db_errors.service.test.js
Labels: enhancement

#182 Fix admin requests to regime paths return 500
  app/services/authorisation.service.js
  db/seeds/02_authorised_systems.js
  test/controllers/admin/regimes.controller.test.js
  test/services/authorisation.service.test.js
  test/services/show_authorised_system.service.test.js
  test/support/helpers/authorised_system.helper.js
  test/support/helpers/route.helper.js
Labels: bug

#157 Add version info to responses plugin
  app/plugins/index.js
  app/plugins/version_info.plugin.js
  server.js
  test/features/version_info.test.js
Labels: enhancement

#180 Fix waterundertaker validation on charge
  app/translators/calculate_charge.translator.js
  test/translators/calculate_charge.translator.test.js
Labels: bug

#183 Fix incorrect transaction validation
  app/services/calculate_charge.service.js
  app/services/create_transaction.service.js
Labels: bug

#184 Fix missing client Id in create transaction
  app/presenters/create_transaction.presenter.js
  test/presenters/create_transaction.presenter.test.js
Labels: bug

#185 Fix not requiring area/region code in transaction create
  app/translators/transaction.translator.js
  test/translators/transaction.translator.test.js
Labels: bug

#181 Generate bill run
  app/controllers/presroc/bill_runs.controller.js
  app/models/invoice.model.js
  app/services/generate_bill_run.service.js
  app/services/index.js
  app/services/validate_bill_run.service.js
  db/migrations/20210131154912_alter_bill_runs.js
  db/migrations/20210203155540_alter_invoices.js
  test/services/generate_bill_run.service.test.js
  test/services/validate_bill_run.service.test.js
  test/support/helpers/rules_service.helper.js
Labels: enhancement

#188 Fix bill runs credit and invoice count column type
  db/migrations/20210131154912_alter_bill_runs.js
Labels: bug

#186 Add stand-in bill run /status endpoint
  app/controllers/presroc/bill_runs.controller.js
  app/routes/bill_run.routes.js
  test/controllers/presroc/bill_runs.controller.test.js
Labels: enhancement

#187 Add bill run status service
  app/services/bill_run_status.service.js
  app/services/index.js
  test/services/bill_run_status.service.test.js
Labels: enhancement

#191 Fix section126Factor in CalculateChargeTranslator
  app/translators/calculate_charge.translator.js
  test/translators/calculate_charge.translator.test.js
Labels: bug

#190 Add bill run status presenter
  app/presenters/bill_run_status.presenter.js
  app/presenters/index.js
  app/services/bill_run_status.service.js
  test/presenters/bill_run_status.presenter.test.js
Labels: enhancement

#193 Fix bill run generate request type (PATCH vs POST)
  app/routes/bill_run.routes.js
  test/controllers/presroc/bill_runs.controller.test.js
Labels: bug

#192 Hook bill run status service to controller
  app/controllers/presroc/bill_runs.controller.js
  test/controllers/presroc/bill_runs.controller.test.js
Labels: enhancement

#195 Fix minimum charge issues in generate bill run
  app/models/invoice.model.js
  app/services/calculate_minimum_charge.service.js
  app/services/generate_bill_run.service.js
  test/services/calculate_minimum_charge.service.test.js
  test/services/generate_bill_run.service.test.js
  test/support/helpers/rules_service.helper.js
Labels: bug

#197 Validate water undertaker is boolean in charge
  app/translators/calculate_charge.translator.js
  test/translators/calculate_charge.translator.test.js
Labels: enhancement

#196 Output generate bill run timing
  app/controllers/presroc/bill_runs.controller.js
  app/services/generate_bill_run.service.js
  test/services/generate_bill_run.service.test.js
Labels: enhancement

#194 Fix Invoice deminimis query modifier
  app/models/invoice.model.js
  test/models/invoice.model.test.js
  test/services/generate_bill_run.service.test.js
  test/support/helpers/invoice.helper.js
Labels: bug

#198 Create View Bill Run Service
  app/models/bill_run.model.js
  app/presenters/index.js
  app/presenters/view_bill_run.presenter.js
  app/services/index.js
  app/services/view_bill_run.service.js
  test/services/view_bill_run.service.test.js
Labels: enhancement

#199 Add test only bill run generator
  app/controllers/admin/test/test_bill_run.controller.js
  app/controllers/index.js
  app/plugins/router.plugin.js
  app/routes/index.js
  app/routes/test.routes.js
  test/controllers/admin/test/test_bill_run.controller.test.js
  test/support/generators/README.md
  test/support/generators/bill_run.generator.js
  test/support/generators/index.js
  test/support/helpers/route.helper.js
Labels: enhancement

#202 Title case loss, season & source values in charge
  app/translators/calculate_charge.translator.js
  test/translators/calculate_charge.translator.test.js
Labels: enhancement

#203 Fix missing bill run to licence relationship
  app/models/bill_run.model.js
Labels: bug

#200 Fix update of invoice for minimum charge
  app/services/bill_run.service.js
  app/services/create_minimum_charge_adjustment.service.js
  app/services/generate_bill_run.service.js
  test/services/bill_run.service.test.js
  test/services/generate_bill_run.service.test.js
Labels: bug

#206 Add bill run ID to generate bill run time logging
  app/services/generate_bill_run.service.js
Labels: enhancement

#207 Add error handling to GenerateBillRunService
  app/services/generate_bill_run.service.js
  test/services/generate_bill_run.service.test.js
  test/support/generators/bill_run.generator.js
Labels: housekeeping

#208 Amend transactions and invoices tables
  app/models/invoice.model.js
  db/migrations/20210215154015_alter_transactions_and_invoices.js
  test/models/invoice.model.test.js
Labels: enhancement

#205 Minimum charge invoice flag
  app/services/generate_bill_run.service.js
  app/services/view_bill_run.service.js
  db/migrations/20210212160135_alter_invoices.js
  test/services/generate_bill_run.service.test.js
Labels: enhancement

#209 Add view bill run endpoint using ViewBillRunService
  app/controllers/presroc/bill_runs.controller.js
  app/routes/bill_run.routes.js
  test/controllers/presroc/bill_runs.controller.test.js
Labels: enhancement

#210 Allow period start to be same as period end date
  app/translators/calculate_charge.translator.js
  test/translators/calculate_charge.translator.test.js
Labels: housekeeping

#211 Add stand-in view bill run transaction endpoint
  app/controllers/presroc/bill_runs.controller.js
  app/routes/bill_run.routes.js
  test/controllers/presroc/bill_runs.controller.test.js
Labels: enhancement

#213 Fix docker build issues due to bill run generator
  .dockerignore
  package.json
Labels: bug

#214 Add support for automated builds in Docker Hub
  Dockerfile
  hooks/README.md
  hooks/build
Labels: housekeeping

#215 Error handling for rules service responses
  .env.example
  .github/workflows/ci.yml
  app/services/rules.service.js
  config/rules_service.config.js
  test/services/rules.service.test.js
Labels: bug, enhancement

#216 Add system user seed
  .env.example
  config/authentication.config.js
  db/seeds/02_authorised_systems.js
Labels: housekeeping

#217 Remove pre-sroc (ruleset) from view bill run
  app/presenters/view_bill_run.presenter.js
Labels: housekeeping

#218 Make transaction tracking properties consistent
  app/models/bill_run.model.js
  app/models/invoice.model.js
  app/presenters/view_bill_run.presenter.js
  app/services/bill_run.service.js
  app/services/calculate_minimum_charge.service.js
  app/services/generate_bill_run.service.js
  app/services/invoice.service.js
  app/services/licence.service.js
  app/services/view_bill_run.service.js
  db/migrations/20210219130054_alter_bill_runs.js
  db/migrations/20210219130102_alter_invoices.js
  db/migrations/20210219130108_alter_licences.js
  test/services/bill_run.service.test.js
  test/services/generate_bill_run.service.test.js
  test/services/invoice.service.test.js
  test/services/licence.service.test.js
  test/services/view_bill_run.service.test.js
  test/support/helpers/invoice.helper.js
Labels: housekeeping

#220 Add seed run script to package.json
  .vscode/tasks.json
  package.json
Labels: housekeeping

#219 Initial Delete Invoice controller and endpoint
  app/controllers/index.js
  app/controllers/presroc/invoices.controller.js
  app/plugins/router.plugin.js
  app/routes/index.js
  app/routes/invoice.routes.js
  test/controllers/presroc/invoices.controller.test.js
Labels: enhancement

#204 Add get bill run plugin
  app/controllers/admin/test/test_bill_run.controller.js
  app/plugins/bill_run.plugin.js
  app/plugins/index.js
  app/routes/test.routes.js
  app/services/index.js
  app/services/request_bill_run.service.js
  server.js
  test/controllers/admin/test/test_bill_run.controller.test.js
  test/controllers/presroc/bill_runs.controller.test.js
  test/features/find_validate_bill_runs.test.js
  test/services/request_bill_run.service.test.js
  test/support/helpers/route.helper.js
Labels: enhancement

#223 Add admin test view transaction endpoint
  app/controllers/admin/test/test_transactions.controller.js
  app/controllers/index.js
  app/routes/test.routes.js
  app/services/index.js
  app/services/show_transaction.service.js
  test/controllers/admin/test/test_transactions_controller.test.js
  test/services/show_transaction.service.test.js
Labels: enhancement

#227 Amend remove invoice route
  app/controllers/index.js
  app/controllers/presroc/bill_runs_invoices.controller.js
  app/plugins/router.plugin.js
  app/routes/bill_run_invoice.routes.js
  app/routes/index.js
  app/routes/invoice.routes.js
  test/controllers/presroc/bill_runs_invoices.controller.test.js
Labels: housekeeping

#224 Add stand-in view bill run invoice endpoint
  app/controllers/presroc/bill_runs_invoices.controller.js
  app/routes/bill_run_invoice.routes.js
  test/controllers/presroc/bill_runs_invoices.controller.test.js
Labels: enhancement, on hold

#228 Add references to licences and transactions tables
  db/migrations/20210223115103_alter_licences.js
  db/migrations/20210223145653_alter_transactions.js
  test/features/bigint_handling.test.js
  test/services/licence.service.test.js
  test/support/helpers/index.js
  test/support/helpers/licence.helper.js
  test/support/helpers/transaction.helper.js
Labels: enhancement

#229 Add view transaction presenter
  app/presenters/index.js
  app/presenters/view_transaction.presenter.js
Labels: enhancement

#231 Fix inconsistent test bill run controller name
  app/controllers/admin/test/test_bill_runs.controller.js
  app/controllers/index.js
  app/routes/test.routes.js
  test/controllers/admin/test/test_bill_runs.controller.test.js
Labels: housekeeping

#232 Move bill run transaction actions to own ctrlr
  app/controllers/index.js
  app/controllers/presroc/bill_runs.controller.js
  app/controllers/presroc/bill_runs_transactions.controller.js
  app/plugins/router.plugin.js
  app/routes/bill_run.routes.js
  app/routes/bill_run_transaction.routes.js
  app/routes/index.js
  test/controllers/presroc/bill_runs.controller.test.js
  test/controllers/presroc/bill_runs_transactions.controller.test.js
Labels: housekeeping

#233 Remove redundant bill run 'gets' and 'checks'
  app/controllers/presroc/bill_runs.controller.js
  app/services/bill_run_status.service.js
  app/services/generate_bill_run.service.js
  app/services/generate_bill_run_validation.service.js
  app/services/index.js
  app/services/validate_bill_run.service.js
  test/controllers/presroc/bill_runs.controller.test.js
  test/services/bill_run_status.service.test.js
  test/services/generate_bill_run.service.test.js
  test/services/generate_bill_run_validation.service.js
  test/services/validate_bill_run.service.test.js
  test/services/view_bill_run.service.test.js
Labels: housekeeping

#234 Fix bill run $editable() method
  app/models/bill_run.model.js
  test/models/bill_run.model.test.js
Labels: bug

#230 Add view licence presenter
  app/presenters/index.js
  app/presenters/view_licence.presenter.js
Labels: enhancement

#236 Add bill run invoice validator
  app/services/fetch_and_validate_bill_run_invoice.service.js
  app/services/index.js
  test/services/fetch_and_validate_bill_run_invoice.service.test.js
Labels: enhancement

#235 Add stand-in approve bill run endpoint
  app/controllers/presroc/bill_runs.controller.js
  app/routes/bill_run.routes.js
  test/controllers/presroc/bill_runs.controller.test.js
Labels: enhancement

#237 Add approve bill run service
  app/models/bill_run.model.js
  app/services/approve_bill_run.service.js
  app/services/index.js
  test/services/approve_bill_run.service.test.js
Labels: enhancement

#226 Add view invoice presenter
  app/presenters/index.js
  app/presenters/view_invoice.presenter.js
  test/presenters/view_invoice.presenter.test.js
Labels: enhancement

#239 Hook up approve bill run endpoint to service
  app/controllers/presroc/bill_runs.controller.js
  test/controllers/presroc/bill_runs.controller.test.js
Labels: enhancement

#240 Correct view bill run zero line count property
  app/presenters/view_bill_run.presenter.js
  test/services/view_bill_run.service.test.js
Labels: housekeeping

#241 Fix invoiceValue for minimum charge
  app/services/generate_bill_run.service.js
  test/services/generate_bill_run.service.test.js
Labels: bug

#221 Create Delete Invoice Service
  app/models/invoice.model.js
  app/services/delete_invoice.service.js
  app/services/index.js
  test/services/delete_invoice.service.test.js
Labels: enhancement

#242 Housekeeping - correct test file name
  test/services/generate_bill_run_validation.service.test.js
Labels: housekeeping

#243 Add view bill run invoice service
  app/models/licence.model.js
  app/presenters/view_invoice.presenter.js
  app/services/index.js
  app/services/view_bill_run_invoice.service.js
  test/models/licence.model.test.js
  test/presenters/view_invoice.presenter.test.js
  test/services/view_bill_run_invoice.service.test.js
Labels: enhancement

#245 Add stand-in send bill run endpoint
  app/controllers/presroc/bill_runs.controller.js
  app/models/bill_run.model.js
  app/routes/bill_run.routes.js
  test/controllers/presroc/bill_runs.controller.test.js
  test/models/bill_run.model.test.js
Labels: enhancement
