Repository DEFRA/sroc-charging-module-api, pull requests merged in 2021-05, with the labels that each got.

#396 Fix DB rebuild vscode task
  .vscode/tasks.json
Labels: bug

#398 Correct await async usage in RequestBillRunService
  app/services/plugins/request_bill_run.service.js
Labels: housekeeping

#387 Create Invoice Rebilling Validation Service
  app/services/index.js
  app/services/invoice_rebilling_validation.service.js
  test/services/invoice_rebilling_validation.service.test.js
Labels: enhancement

#397 Fix missing customer validations
  app/translators/customer.translator.js
  test/translators/customer.translator.test.js
Labels: bug

#399 Rename bill run plugin to be more consistent
  app/plugins/index.js
  app/plugins/request_bill_run.plugin.js
  server.js
Labels: housekeeping

#395 Create rebilling initialise service
  app/models/invoice.model.js
  app/presenters/index.js
  app/presenters/invoice_rebilling.presenter.js
  app/services/index.js
  app/services/invoice_rebilling_initialise.service.js
  db/migrations/20210430144052_alter_invoices.js
  test/presenters/invoice_rebilling.presenter.test.js
  test/services/invoice_rebilling_initialise.service.test.js
Labels: enhancement

#402 Create InvoiceRebillingCreateTransactionService
  app/services/index.js
  app/services/invoice_rebilling_create_transaction.service.js
  test/services/invoice_rebilling_create_transaction.service.test.js
Labels: enhancement

#403 Create Invoice Rebilling Create Licence Service
  app/services/index.js
  app/services/invoice_rebilling_create_licence.service.js
  test/services/invoice_rebilling_create_licence.service.test.js
Labels: enhancement

#406 Create Invoice Rebilling Service
  app/models/invoice.model.js
  app/services/index.js
  app/services/invoice_rebilling.service.js
  app/services/invoice_rebilling_create_transaction.service.js
  test/services/invoice_rebilling.service.test.js
  test/services/invoice_rebilling_create_transaction.service.test.js
  test/support/helpers/invoice.helper.js
Labels: enhancement

#407 Add rebilling validation for cancel invoices
  app/services/invoice_rebilling_validation.service.js
  test/services/invoice_rebilling_validation.service.test.js
Labels: enhancement

#408 Update Invoice Rebilling Controller
  app/controllers/presroc/bill_runs_invoices.controller.js
  test/controllers/presroc/bill_runs_invoices.controller.test.js
Labels: enhancement

#411 Add auth scope to invoice rebill endpoint
  app/routes/bill_run_invoice.routes.js
  test/controllers/presroc/bill_runs_invoices.controller.test.js
  test/support/helpers/authorised_system.helper.js
Labels: housekeeping

#414 Add db reset package.json script
  .vscode/tasks.json
  db/clean.database.js
  db/create.database.js
  package.json
Labels: enhancement

#417 Exclude rebilling invoices from deminimis and minimum charge calculation
  app/models/invoice.model.js
  test/models/invoice.model.test.js
Labels: enhancement

#418 Prevent duplicate billing
  app/services/invoice_rebilling_validation.service.js
  test/services/invoice_rebilling_validation.service.test.js
Labels: enhancement

#421 Add rebilling info to view bill run response
  app/presenters/view_bill_run_invoice.presenter.js
  test/presenters/view_bill_run.presenter.test.js
Labels: enhancement

#422 Add rebilling info to ViewInvoicePresenter
  app/presenters/view_invoice.presenter.js
  test/presenters/view_invoice.presenter.test.js
Labels: enhancement

#420 Add support to seed test authorised system
  .env.example
  config/authentication.config.js
  db/seeds/02_authorised_systems.js
Labels: enhancement

#416 Add update (PATCH) authorised systems endpoint
  app/controllers/admin/authorised_systems.controller.js
  app/routes/authorised_system.routes.js
  app/services/index.js
  app/services/update_authorised_system.service.js
  test/controllers/admin/authorised_systems.controller.test.js
  test/services/update_authorised_system.service.test.js
Labels: housekeeping

#423 Add rebilling fields to View Bill Run query
  app/services/view_bill_run.service.js
Labels: enhancement

#424 Add rebilling fields to View Bill Run Invoice query
  app/services/view_bill_run_invoice.service.js
Labels: enhancement

#426 Add AuthorisationService to plugins folder
  app/services/index.js
  app/services/plugins/authorisation.service.js
  test/services/plugins/authorisation.service.test.js
Labels: housekeeping

#425 Include pending changes in SendCustomerFileService
  app/services/index.js
  app/services/prepare_customer_file.service.js
  app/services/send_customer_file.service.js
  test/services/prepare_customer_file.service.test.js
  test/services/send_customer_file.service.test.js
Labels: enhancement

#429 Revised Admin Send Transaction File endpoint
  app/controllers/admin/bill_runs.controller.js
  app/controllers/index.js
  app/routes/bill_run.routes.js
  app/services/plugins/request_bill_run.service.js
  test/controllers/admin/bill_runs.controller.test.js
  test/services/plugins/request_bill_run.service.test.js
Labels: enhancement

#431 Merge VSCode db setup tasks
  .vscode/tasks.json
  README.md
Labels: housekeeping

#430 Add nuke-db npm script
  .vscode/tasks.json
  db/drop.database.js
  package.json
Labels: enhancement

#432 Squash migration scripts before Go Live
  db/migrations/20201012150934_create_authorised_systems.js
  db/migrations/20201127100927_alter_authorised_systems.js
  db/migrations/20201215095327_alter_bill_runs.js
  db/migrations/20201217145238_alter_transactions.js
  db/migrations/20201218153444_alter_authorised_systems.js
  db/migrations/20201224094044_alter_bill_runs.js
  db/migrations/20210105161244_create_invoices.js
  db/migrations/20210105161316_alter_transactions.js
  db/migrations/20210108140838_alter_transactions.js
  db/migrations/20210112121936_alter_transactions.js
  db/migrations/20210114152743_alter_bill_runs.js
  db/migrations/20210119130726_alter_invoices.js
  db/migrations/20210126164808_alter_invoices.js
  db/migrations/20210126165247_alter_licences.js
  db/migrations/20210126165650_alter_transactions.js
  db/migrations/20210126170439_alter_bill_runs.js
  db/migrations/20210127145707_alter_transactions.js
  db/migrations/20210131154912_alter_bill_runs.js
  db/migrations/20210203155540_alter_invoices.js
  db/migrations/20210212160135_alter_invoices.js
  db/migrations/20210215154015_alter_transactions_and_invoices.js
  db/migrations/20210219130054_alter_bill_runs.js
  db/migrations/20210219130102_alter_invoices.js
  db/migrations/20210219130108_alter_licences.js
  db/migrations/20210223115103_alter_licences.js
  db/migrations/20210223145653_alter_transactions.js
  db/migrations/20210302125559_create_customers.js
  db/migrations/20210304112943_alter_sequence_counters.js
  db/migrations/20210304172629_alter_invoices.js
  db/migrations/20210304235307_alter_sequence_counters.js
  db/migrations/20210305132500_alter_bill_runs.js
  db/migrations/20210406075137_alter_transactions.js
  db/migrations/20210407142349_alter_sequence_counters.js
  db/migrations/20210413154851_alter_customers.js
  db/migrations/20210416143924_alter_customers.js
  db/migrations/20210421110628_alter_customer_files.js
  db/migrations/20210430144052_alter_invoices.js
  db/migrations/20210518115800_add_pgcrypto_extension.js
  db/migrations/20210518115801_create_update_timestamp_trigger.js
  db/migrations/20210518115802_create_regimes.js
  db/migrations/20210518115803_create_authorised_systems.js
  db/migrations/20210518115804_create_authorised_systems_regimes.js
  db/migrations/20210518115805_create_sequence_counters.js
  db/migrations/20210518115806_create_customer_files.js
  db/migrations/20210518115807_create_customers.js
  db/migrations/20210518115808_create_exported_customers.js
  db/migrations/20210518115809_create_bill_runs.js
  db/migrations/20210518115810_create_invoices.js
  db/migrations/20210518115811_create_licences.js
  db/migrations/20210518115812_create_transactions.js
Labels: housekeeping

#433 Create BoomNotifier
  app/lib/boom_notifier.js
  app/lib/index.js
  test/lib/boom_notifier.test.js
Labels: enhancement

#434 Create AdminSendTransactionFileService
  app/services/admin_send_transaction_file.service.js
  app/services/index.js
  test/services/admin_send_transaction_file.service.test.js
Labels: enhancement

#435 Use admin send transaction file service in endpoint
  app/controllers/admin/bill_runs.controller.js
  app/services/admin_send_transaction_file.service.js
  test/controllers/admin/bill_runs.controller.test.js
Labels: enhancement

#436 Remove rebilling endpoint feature flag
  app/routes/bill_run_invoice.routes.js
Labels: housekeeping

#437 Fix defects in customer data validation
  app/translators/customer.translator.js
  db/migrations/20210518115807_create_customers.js
  test/services/create_customer_details.service.test.js
Labels: bug

#439 Fix missing admin auth scope on bill run /send
  app/routes/bill_run.routes.js
  test/controllers/admin/bill_runs.controller.test.js
Labels: bug

#442 Develop Request Licence plugin
  app/plugins/index.js
  app/plugins/request_licence.plugin.js
  app/services/index.js
  app/services/plugins/request_licence.service.js
  server.js
  test/services/plugins/request_licence.service.test.js
Labels: enhancement

#440 Add filtered routes service
  app/plugins/router.plugin.js
  app/routes/bill_run_invoice.routes.js
  app/services/index.js
  app/services/plugins/filter_routes.service.js
  test/services/plugins/filter_routes.service.test.js
Labels: enhancement

#443 Fix generated bill run status after add trans.
  app/models/bill_run.model.js
  test/services/create_transaction.service.test.js
  test/support/helpers/bill_run.helper.js
Labels: bug

#444 Delete licence create initial endpoint
  app/controllers/index.js
  app/controllers/presroc/bill_runs_licences.controller.js
  app/plugins/router.plugin.js
  app/routes/bill_run_licence.routes.js
  app/routes/index.js
  test/controllers/presroc/bill_runs_licences.controller.test.js
Labels: enhancement
