Repository DEFRA/sroc-charging-module-api, pull requests merged in 2021-07, with the labels that each got.

#471 Fix broken Docker build
  .dockerignore
Labels: bug

#475 Fix - Rebilling for same customer causes error
  app/models/invoice.model.js
  app/services/invoice_rebilling_copy.service.js
  app/services/invoice_rebilling_create_transaction.service.js
  db/migrations/20210706135346_alter_invoices.js
  test/services/invoice_rebilling_create_transaction.service.test.js
  test/services/invoice_rebilling_initialise.service.test.js
  test/support/helpers/invoice.helper.js
Labels: bug

#476 Create table body presenter
  app/presenters/index.js
  app/presenters/table_body.presenter.js
  test/presenters/table_body.presenter.test.js
Labels: enhancement

#477 Create TransformTableToFile service
  app/presenters/index.js
  app/presenters/table_file.presenter.js
  app/services/index.js
  app/services/streams/stream_transform_using_presenter.service.js
  app/services/transform_table_to_file.service.js
  test/presenters/table_file.presenter.test.js
  test/services/streams/stream_transform_using_presenter.service.test.js
  test/services/transform_table_to_file.service.test.js
Labels: enhancement

#480 Create table export service
  app/services/export_table.service.js
  app/services/index.js
  test/services/export_table.service.test.js
Labels: enhancement

#491 Include licence no. for min. charge in trans file
  app/presenters/transaction_file_body.presenter.js
  test/presenters/transaction_file_body.presenter.test.js
Labels: enhancement

#490 Rework bill run, licence and invoice creation test helpers
  test/services/validate_bill_run_licence.service.test.js
  test/support/helpers/index.js
  test/support/helpers/new_bill_run.helper.js
  test/support/helpers/new_invoice.helper.js
  test/support/helpers/new_licence.helper.js
Labels: housekeeping

#494 Remove invalid min. charge model tests
  test/models/invoice.model.test.js
Labels: housekeeping

#496 Rework test transaction helper
  test/controllers/presroc/bill_runs_invoices.controller.test.js
  test/support/helpers/index.js
  test/support/helpers/new_transaction.helper.js
  test/support/helpers/regime.helper.js
Labels: housekeeping
