Repository DEFRA/sroc-charging-module-api, pull requests merged in 2021-06, with the labels that each got.

#446 Develop initial DeleteLicenceService
  app/services/delete_licence.service.js
  app/services/index.js
  test/services/delete_licence.service.test.js
Labels: enhancement

#448 Fix Client ID unique constraint for rebilling
  app/services/invoice_rebilling_create_transaction.service.js
  test/services/invoice_rebilling_create_transaction.service.test.js
Labels: bug

#449 Refactor bill run editable and add patchable
  app/models/bill_run.model.js
  app/services/plugins/request_bill_run.service.js
  test/controllers/presroc/bill_runs.controller.test.js
  test/models/bill_run.model.test.js
  test/services/plugins/request_bill_run.service.test.js
Labels: enhancement

#450 Fix minimum charge being calculated at wrong level
  app/models/invoice.model.js
  app/services/calculate_minimum_charge.service.js
  test/services/calculate_minimum_charge.service.test.js
Labels: bug

#445 Create ValidateBillRunLicenceService
  app/models/invoice.model.js
  app/services/index.js
  app/services/validate_bill_run_licence.service.js
  test/models/invoice.model.test.js
  test/services/validate_bill_run_licence.service.test.js
Labels: enhancement

#451 Add delete licence services to controller
  app/controllers/presroc/bill_runs_licences.controller.js
  test/controllers/presroc/bill_runs_licences.controller.test.js
Labels: enhancement

#455 Fix missing flags on rebill invoices
  app/services/invoice_rebilling_initialise.service.js
  test/services/invoice_rebilling_initialise.service.test.js
Labels: bug

#456 Link rebilled transaction to original transaction
  app/presenters/view_transaction.presenter.js
  app/services/invoice_rebilling_create_transaction.service.js
  app/services/view_bill_run_invoice.service.js
  db/migrations/20210609165720_alter_transactions.js
  test/presenters/view_transaction.presenter.test.js
  test/services/invoice_rebilling_create_transaction.service.test.js
Labels: enhancement

#457 Housekeeping - Update lib file names
  app/controllers/admin/customers.controller.js
  app/lib/base_notifier.lib.js
  app/lib/boom_notifier.js
  app/lib/boom_notifier.lib.js
  app/lib/index.js
  app/lib/jwt_strategy.lib.js
  app/lib/request_notifier.lib.js
  app/lib/static_lookup.lib.js
  app/lib/task_notifier.lib.js
  app/plugins/airbrake.plugin.js
  app/plugins/request_notifier.plugin.js
  app/services/admin_send_transaction_file.service.js
  app/services/delete_bill_run.service.js
  app/services/delete_invoice.service.js
  app/services/delete_licence.service.js
  app/services/generate_bill_run.service.js
  app/services/invoice_rebilling.service.js
  app/services/send_customer_file.service.js
  app/services/send_transaction_file.service.js
  app/tasks/customer_files.task.js
  app/tasks/task_runner.js
  app/translators/customer.translator.js
  server.js
  test/features/add_notifier_to_requests.test.js
  test/lib/base_notifier.lib.test.js
  test/lib/boom_notifier.lib.test.js
  test/lib/request_notifier.lib.test.js
  test/lib/task_notifier.lib.test.js
  test/tasks/task_runner.test.js
Labels: housekeeping

#460 Enable rebilling
  app/routes/bill_run_invoice.routes.js
Labels: enhancement

#453 Recalculate invoice on delete licence
  app/models/invoice.model.js
  app/services/delete_licence.service.js
  test/models/invoice.model.test.js
  test/services/delete_licence.service.test.js
Labels: enhancement

#464 Fix - protect bill run when rebilling
  app/services/invoice_rebilling_initialise.service.js
  test/services/invoice_rebilling_initialise.service.test.js
Labels: bug

#465 Recalculate bill run on delete licence
  app/services/delete_invoice.service.js
  app/services/delete_licence.service.js
  test/services/delete_licence.service.test.js
Labels: enhancement

#463 Refactor InvoiceRebillingService to do more
  app/controllers/presroc/bill_runs_invoices.controller.js
  app/services/index.js
  app/services/invoice_rebilling.service.js
  app/services/invoice_rebilling_copy.service.js
  app/services/invoice_rebilling_initialise.service.js
  test/controllers/presroc/bill_runs_invoices.controller.test.js
  test/services/invoice_rebilling.service.test.js
  test/services/invoice_rebilling_copy.service.test.js
  test/services/invoice_rebilling_initialise.service.test.js
Labels: housekeeping

#467 Remove hpal support and update server.js
  Dockerfile
  app/plugins/hpal_debug.plugin.js
  app/plugins/index.js
  app/server.js
  index.js
  package-lock.json
  package.json
  sonar-project.properties
  test/controllers/admin/authorised_systems.controller.test.js
  test/controllers/admin/bill_runs.controller.test.js
  test/controllers/admin/customers.controller.test.js
  test/controllers/admin/health/airbrake.controller.test.js
  test/controllers/admin/health/database.controller.test.js
  test/controllers/admin/regimes.controller.test.js
  test/controllers/admin/test/test_bill_runs.controller.test.js
  test/controllers/admin/test/test_customer_files.controller.test.js
  test/controllers/admin/test/test_transactions_controller.test.js
  test/controllers/not_supported.controller.test.js
  test/controllers/presroc/bill_runs.controller.test.js
  test/controllers/presroc/bill_runs_invoices.controller.test.js
  test/controllers/presroc/bill_runs_licences.controller.test.js
  test/controllers/presroc/bill_runs_transactions.controller.test.js
  test/controllers/presroc/calculate_charge.controller.test.js
  test/controllers/presroc/customer_details.controller.test.js
  test/controllers/root.controller.test.js
  test/features/add_notifier_to_requests.test.js
  test/features/authentication.test.js
  test/features/authorisation.test.js
  test/features/clean_payloads.test.js
  test/features/find_validate_bill_runs.test.js
  test/features/find_validate_invoices.test.js
  test/features/graceful_shutdown.test.js
  test/features/invalid_characters.test.js
  test/features/logging.test.js
  test/features/reject_missing_payloads.test.js
  test/features/routing.test.js
  test/features/sanitise_payloads.test.js
  test/features/version_info.test.js
Labels: housekeeping
