Repository DEFRA/sroc-charging-module-api, pull requests merged in 2021-01, with the labels that each got.

#141 Alter transactions to use BigInts
  db/migrations/20210108140838_alter_transactions.js
  test/features/bigint_handling.test.js
Labels: enhancement

#140 Add invoice model and service
  app/models/base.model.js
  app/models/base_query_builder.js
  app/models/index.js
  app/models/invoice.model.js
  app/models/transaction.model.js
  app/services/calculate_charge.service.js
  app/services/create_transaction.service.js
  app/services/index.js
  app/services/invoice.service.js
  db/migrations/20210105161244_create_invoices.js
  db/migrations/20210105161316_alter_transactions.js
  test/features/bigint_handling.test.js
  test/services/invoice.service.test.js
Labels: enhancement

#143 Change some instances of ' use strict' to 'use strict'
  app/translators/authorised_system.translator.js
  app/translators/bill_run.translator.js
  app/translators/transaction.translator.js
Labels: housekeeping

#145 Add bill run status check to add transaction
  app/models/bill_run.model.js
  app/services/bill_run.service.js
  app/services/create_transaction.service.js
  app/services/index.js
  test/models/bill_run.model.test.js
  test/services/bill_run.service.test.js
  test/services/create_transaction.service.test.js
Labels: enhancement

#146 Add licence model and service
  app/models/index.js
  app/models/invoice.model.js
  app/models/licence.model.js
  app/models/transaction.model.js
  app/services/create_transaction.service.js
  app/services/index.js
  app/services/licence.service.js
  db/migrations/20210111171826_create_licences.js
  db/migrations/20210112121936_alter_transactions.js
  test/features/bigint_handling.test.js
  test/services/licence.service.test.js
Labels: enhancement

#147 Add summary to bill run service
  app/services/bill_run.service.js
  app/services/create_transaction.service.js
  db/migrations/20210114152743_alter_bill_runs.js
  test/services/bill_run.service.test.js
Labels: enhancement

#150 Fix snake case fields in database
  app/models/authorised_system.model.js
  app/models/base.model.js
  app/models/bill_run.model.js
  app/models/invoice.model.js
  app/models/licence.model.js
  app/models/regime.model.js
  app/models/sequence_counter.model.js
  app/models/transaction.model.js
  app/services/invoice.service.js
  app/services/licence.service.js
  db/index.js
  db/migrations/20201217145238_alter_transactions.js
  knexfile.application.js
Labels: housekeeping

#154 Fix missing knexfile.application.js to docker
  .dockerignore
Labels: bug

#151 Create Generate Bill Run Summary endpoint
  app/controllers/presroc/bill_runs.controller.js
  app/models/bill_run.model.js
  app/models/invoice.model.js
  app/routes/bill_run.routes.js
  app/services/generate_bill_run.service.js
  app/services/index.js
  db/migrations/20210119130726_alter_invoices.js
  test/controllers/presroc/bill_runs.controller.test.js
  test/services/generate_bill_run.service.test.js
  test/support/helpers/index.js
  test/support/helpers/invoice.helper.js
Labels: enhancement

#155 Add git and docker tags to Docker image
  .vscode/tasks.json
  Dockerfile
  docker-compose.yml
Labels: enhancement

#156 Create Minimum Charge Adjustment service
  app/services/create_minimum_charge_adjustment.service.js
  app/services/index.js
  test/services/create_minimum_charge_adjustment.service.test.js
Labels: enhancement

#162 Add trans. region must match bill run check
  app/services/bill_run.service.js
  test/services/bill_run.service.test.js
Labels: enhancement

#165 Minimum charge database changes
  app/services/bill_run.service.js
  app/services/create_minimum_charge_adjustment.service.js
  app/services/invoice.service.js
  app/services/licence.service.js
  app/translators/transaction.translator.js
  db/migrations/20210126164808_alter_invoices.js
  db/migrations/20210126165247_alter_licences.js
  db/migrations/20210126165650_alter_transactions.js
  db/migrations/20210126170439_alter_bill_runs.js
  test/services/bill_run.service.test.js
  test/services/create_minimum_charge_adjustment.service.test.js
  test/services/invoice.service.test.js
  test/services/licence.service.test.js
  test/translators/transaction.translator.test.js
Labels: housekeeping

#163 Fix create bill run returns 500 if region missing
  app/translators/bill_run.translator.js
  test/services/create_bill_run.service.test.js
  test/translators/bill_run.translator.test.js
Labels: bug

#166 Fix 500 error when compensation charge set to true
  app/translators/calculate_charge.translator.js
Labels: bug

#168 Prevent duplicate transactions with clientID check
  db/migrations/20210127145707_alter_transactions.js
  test/services/create_transaction.service.test.js
Labels: enhancement

#169 Fix ensure volume is required for charge and trans
  app/translators/calculate_charge.translator.js
Labels: bug

#164 Calculate Minimum Charge Transaction service
  app/models/invoice.model.js
  app/services/calculate_minimum_charge.service.js
  app/services/create_minimum_charge_adjustment.service.js
  app/services/index.js
  test/services/calculate_minimum_charge.service.test.js
  test/services/create_minimum_charge_adjustment.service.test.js
Labels: enhancement

#170 Fix Joi validations using US date format
  app/translators/calculate_charge.translator.js
  package-lock.json
  package.json
  test/translators/calculate_charge.translator.test.js
Labels: bug

#173 Refactor cloning in bill runs ctrlr test
  test/controllers/presroc/bill_runs.controller.test.js
Labels: housekeeping

#176 Add uuid4 generator to test GeneralHelper
  test/controllers/admin/authorised_systems.controller.test.js
  test/controllers/admin/regimes.controller.test.js
  test/presenters/create_bill_run.presenter.test.js
  test/presenters/create_transaction.presenter.test.js
  test/services/bill_run.service.test.js
  test/services/create_transaction.service.test.js
  test/services/generate_bill_run.service.test.js
  test/services/show_authorised_system.service.test.js
  test/services/show_regime.service.test.js
  test/support/helpers/general.helper.js
  test/translators/bill_run.translator.test.js
  test/translators/transaction.translator.test.js
Labels: housekeeping

#175 Add new test transaction helper
  test/services/create_transaction.service.test.js
  test/support/helpers/index.js
  test/support/helpers/transaction.helper.js
Labels: housekeeping

#174 Add minimum charge to generate bill run service
  app/models/bill_run.model.js
  app/services/bill_run.service.js
  app/services/generate_bill_run.service.js
  test/controllers/presroc/bill_runs.controller.test.js
  test/services/bill_run.service.test.js
  test/services/generate_bill_run.service.test.js
Labels: enhancement
