Repository DEFRA/sroc-charging-module-api, pull requests merged in 2021-08, with the labels that each got.

#493 Fix invoice min. charge flag when licence deleted
  app/models/invoice.model.js
  app/services/delete_licence.service.js
  test/models/invoice.model.test.js
  test/services/delete_licence.service.test.js
Labels: bug

#497 Test helpers cascade changes upwards
  test/controllers/presroc/bill_runs_invoices.controller.test.js
  test/services/validate_bill_run_licence.service.test.js
  test/support/helpers/new_bill_run.helper.js
  test/support/helpers/new_invoice.helper.js
  test/support/helpers/new_licence.helper.js
  test/support/helpers/new_transaction.helper.js
  test/support/test/helpers/new_bill_run.helper.test.js
  test/support/test/helpers/new_invoice.helper.test.js
  test/support/test/helpers/new_licence.helper.test.js
  test/support/test/helpers/new_transaction.helper.test.js
Labels: housekeeping

#499 Test helpers pass all changes up
  test/support/helpers/new_bill_run.helper.js
  test/support/helpers/new_invoice.helper.js
  test/support/helpers/new_licence.helper.js
  test/support/test/helpers/new_invoice.helper.test.js
  test/support/test/helpers/new_licence.helper.test.js
  test/support/test/helpers/new_transaction.helper.test.js
Labels: housekeeping

#500 Enable delete licence in production
  app/routes/bill_run_licence.routes.js
Labels: enhancement

#506 Specify full key when sending to S3 bucket
  app/services/send_customer_file.service.js
  app/services/send_file_to_s3.service.js
  app/services/send_transaction_file.service.js
  test/services/send_customer_file.service.test.js
  test/services/send_file_to_s3.service.test.js
  test/services/send_transaction_file.service.test.js
Labels: housekeeping

#501 Create `DataExportService`
  app/services/data_export.service.js
  app/services/export_table.service.js
  app/services/index.js
  test/services/data_export.service.test.js
  test/services/export_table.service.test.js
Labels: enhancement

#507 Create data export endpoint
  app/controllers/admin/test/test_data_export.controller.js
  app/controllers/index.js
  app/routes/test.routes.js
  app/services/data_export.service.js
  test/controllers/admin/test/test_data_export.controller.test.js
Labels: enhancement

#505 Add data export task
  app/tasks/data_export.task.js
  app/tasks/index.js
  package.json
  test/tasks/data_export.task.test.js
Labels: enhancement

#508 Add logging to `DataExportService`
  app/services/data_export.service.js
  test/services/data_export.service.test.js
Labels: enhancement

#510 Add `DataExportTask` to `TaskRunner`
  app/tasks/task_runner.js
Labels: enhancement

#511 Fix proxy config defect
  .env.example
  app/services/rules.service.js
  docker-compose.yml
Labels: bug

#513 Move controllers from presroc folder
  app/controllers/bill_runs.controller.js
  app/controllers/bill_runs_invoices.controller.js
  app/controllers/bill_runs_licences.controller.js
  app/controllers/bill_runs_transactions.controller.js
  app/controllers/calculate_charge.controller.js
  app/controllers/customer_details.controller.js
  app/controllers/index.js
  app/routes/bill_run.routes.js
  app/routes/bill_run_invoice.routes.js
  app/routes/bill_run_licence.routes.js
  app/routes/bill_run_transaction.routes.js
  app/routes/calculate_charge.routes.js
  app/routes/customer_details.routes.js
  test/controllers/presroc/bill_runs.controller.test.js
  test/controllers/presroc/bill_runs_invoices.controller.test.js
  test/controllers/presroc/bill_runs_licences.controller.test.js
  test/controllers/presroc/bill_runs_transactions.controller.test.js
Labels: housekeeping

#516 CMEA-102: SonarCloud fixes
  app/services/bill_runs/view_bill_run.service.js
  app/services/files/exports/export_data_files.service.js
  app/services/invoices/invoice_rebilling_create_transaction.service.js
  app/services/invoices/invoice_rebilling_validation.service.js
  app/services/invoices/view_invoice.service.js
  app/services/transactions/create_transaction.service.js
Labels: housekeeping

#517 Delete `REMOVE_TMP_FILES` environment variable
  .env.example
  app/services/files/customers/send_customer_file.service.js
  app/services/files/transactions/send_transaction_file.service.js
  config/server.config.js
  test/services/files/customers/send_customer_file.service.test.js
  test/services/files/transactions/send_transaction_file.service.test.js
Labels: housekeeping

#518 Delete files in `ExportDataFilesService`
  app/services/files/exports/export_data_files.service.js
  test/services/files/exports/export_data_files.service.test.js
Labels: enhancement

#521 Fix dependabot builds
  .github/workflows/ci.yml
Labels: bug

#519 Document services folder
  app/services/readme.md
Labels: documentation

#524 Use `npm audit fix to patch` vulnerabilities
  package-lock.json
Labels: security

#525 Add custom sections to CHANGELOG
  .github_changelog_generator
  CHANGELOG.md
Labels: documentation

#526 Remove WIP message from top of README
  README.md
Labels: documentation
