Repository DEFRA/sroc-charging-module-api, pull requests merged in 2022-03, with the labels that each got.

#693 Update `got` to v12
  app/services/charges/request_rules_service_charge.service.js
  package-lock.json
  package.json
  test/services/charges/request_rules_service_charge.service.test.js
Labels: enhancement

#694 Fix transaction file sort order
  app/services/files/transactions/base_generate_transaction_file.service.js
  test/services/files/transactions/generate_presroc_transaction_file.service.test.js
Labels: bug

#695 Move `nock` and `sinon` to `devDependencies`
  package-lock.json
  package.json
Labels: housekeeping

#703 Give consistent "not linked" error responses
  app/services/bill_runs/validate_bill_run_region.service.js
  app/services/invoices/invoice_rebilling_validation.service.js
  test/services/bill_runs/validate_bill_run_region.service.test.js
  test/services/invoices/invoice_rebilling_validation.service.test.js
Labels: housekeeping

#708 Fix creditLineCount undefined in delete invoice
  app/controllers/bill_runs_invoices.controller.js
Labels: bug
