Repository DEFRA/sroc-charging-module-api, pull requests merged in 2022-02, with the labels that each got.

#666 Refactor `GenerateTransactionFileService` into base and presroc services
  app/services/files/transactions/base_generate_transaction_file.service.js
  app/services/files/transactions/generate_presroc_transaction_file.service.js
  app/services/files/transactions/generate_transaction_file.service.js
  app/services/files/transactions/send_transaction_file.service.js
  app/services/index.js
  test/services/files/transactions/base_generate_transaction_file.service.test.js
  test/services/files/transactions/generate_presroc_transaction_file.service.test.js
  test/services/files/transactions/send_transaction_file.service.test.js
Labels: enhancement

#667 Remove duff view bill run transaction endpoint
  app/controllers/bill_runs_transactions.controller.js
  app/routes/bill_run_transaction.routes.js
  test/controllers/bill_runs_transactions.controller.test.js
Labels: housekeeping

#668 Develop sroc transaction file body presenter
  app/presenters/index.js
  app/presenters/transaction_file_presroc_body.presenter.js
  app/presenters/transaction_file_sroc_body.presenter.js
  app/services/files/transactions/generate_presroc_transaction_file.service.js
  test/presenters/transaction_file_presroc_body.presenter.test.js
  test/presenters/transaction_file_sroc_body.presenter.test.js
Labels: enhancement

#669 Amend transaction file head presenter for sroc
  app/presenters/transaction_file_head.presenter.js
  test/presenters/transaction_file_head.presenter.test.js
  test/services/files/transactions/generate_presroc_transaction_file.service.test.js
Labels: enhancement

#671 Add `prorataDays`/`lineAttr3` to sroc charge
  app/translators/calculate_charge_base.translator.js
  app/translators/calculate_charge_presroc.translator.js
  app/translators/calculate_charge_sroc.translator.js
  app/translators/transaction_sroc.translator.js
  test/translators/calculate_charge_sroc.translator.test.js
Labels: enhancement

#670 Generate sroc transaction file service
  app/presenters/transaction_file_sroc_body.presenter.js
  app/services/files/transactions/base_generate_transaction_file.service.js
  app/services/files/transactions/generate_presroc_transaction_file.service.js
  app/services/files/transactions/generate_sroc_transaction_file.service.js
  app/services/files/transactions/send_transaction_file.service.js
  app/services/index.js
  test/presenters/transaction_file_sroc_body.presenter.test.js
  test/services/files/transactions/base_generate_transaction_file.service.test.js
  test/services/files/transactions/generate_sroc_transaction_file.service.test.js
  test/services/files/transactions/send_transaction_file.service.test.js
Labels: enhancement

#681 Add `adjustmentFactor` to sroc validation
  app/translators/calculate_charge_sroc.translator.js
  app/translators/transaction_sroc.translator.js
  test/support/fixtures/calculate_charge/sroc/simple_request.json
  test/support/fixtures/create_transaction/sroc/simple.json
  test/translators/calculate_charge_sroc.translator.test.js
Labels: enhancement

#682 Add `adjustmentFactor` to `RulesServiceSrocPresenter`
  app/presenters/rules_service_sroc.presenter.js
Labels: enhancement

#683 Use `adjustmentFactor` in sroc transaction file
  app/presenters/transaction_file_sroc_body.presenter.js
  app/services/files/transactions/generate_sroc_transaction_file.service.js
  test/presenters/transaction_file_sroc_body.presenter.test.js
  test/services/files/transactions/generate_sroc_transaction_file.service.test.js
Labels: enhancement

#685 Fix date formatting for Node 16.14.0
  app/presenters/base.presenter.js
  test/presenters/base.presenter.test.js
Labels: bug

#684 Additional validation for `waterUndertaker`
  app/translators/calculate_charge_base.translator.js
  app/translators/calculate_charge_presroc.translator.js
  app/translators/calculate_charge_sroc.translator.js
  test/translators/calculate_charge_sroc.translator.test.js
Labels: enhancement

#686 Make sroc factors mandatory
  app/translators/calculate_charge_sroc.translator.js
  test/translators/calculate_charge_sroc.translator.test.js
Labels: enhancement
